run:
  # Concurrency is reduced in order to reduce RAM consumption
  concurrency: 2
  deadline: 20m

issues:
  exclude:
  - .* is always .* # unparam check
  - ^should have a package comment, unless it's in another file for this package$ # golint check
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
  - bodyclose # TODO(dfurman): fix code to pass
  - godox # TODO(dfurman): fix code to pass
  - dogsled # TODO(dfurman): fix code to pass
  - dupl # consumes too much RAM and CPU cycles
  - funlen # TODO(dfurman): fix code to pass
  - gochecknoglobals # incompatible with current conventions
  - gochecknoinits # incompatible with current conventions
  - gocritic # TODO(dfurman): fix code to pass
  - gosec # consumes too much RAM and CPU cycles
  - megacheck # uses staticcheck, which consumes too much RAM and CPU cycles
  - prealloc # premature optimization
  - scopelint # TODO(dfurman): fix code to pass
  - staticcheck # consumes too much RAM and CPU cycles
  - stylecheck # TODO(dfurman): fix code to pass
  - unparam # TODO(dfurman): fix code to pass
  - whitespace # TODO(dfurman): fix code to pass

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  nakedret:
    max-func-lines: 5
