run:
  # Concurrency is reduced in order to reduce RAM consumption
  concurrency: 2
  deadline: 11m
  skip-dirs:
  - extension/pkg/db/cache        # TODO: re-enable when compilation fixed
  - extension/pkg/db/etcd         # TODO: re-enable when compilation fixed
  - extension/pkg/apisrv/client   # TODO: re-enable when compilation fixed

issues:
  exclude:
  - .* is always .* # unparam issue
  - ^should have a package comment, unless it's in another file for this package$ # golint issue
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

# Intentionally disabled linters:
# - dupl consumes too much RAM and CPU cycles
# - gosec consumes too much RAM and CPU cycles
# - megacheck uses staticcheck which consumes too much RAM and CPU cycles
# - prealloc issues are considered premature optimization
# - staticcheck consumes too much RAM and CPU cycles
linters:
  enable-all: true
  disable:
  - dupl
  - gosec
  - megacheck
  - prealloc
  - staticcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  unparam:
    check-exported: true
  nakedret:
    max-func-lines: 5
