run:
  # Concurrency is reduced in order to reduce RAM consumption
  concurrency: 2
  deadline: 20m
  skip-files:
  # Entries below is a workaround for "typecheck" linter. TODO(Daniel): remove when linter fixed/updated
  - .*/go/src/crypto/.*
  - .*/go/src/internal/syscall/unix/.*
  - .*/go/src/net/.*
  - .*/go/src/os/.*
  - .*/go/src/runtime/.*
  - .*/go/src/syscall/.*

issues:
  exclude:
  - .* is always .* # unparam issue
  - ^should have a package comment, unless it's in another file for this package$ # golint issue
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

# Intentionally disabled linters:
# - dupl consumes too much RAM and CPU cycles
# - gosec consumes too much RAM and CPU cycles
# - megacheck uses staticcheck which consumes too much RAM and CPU cycles
# - prealloc issues are considered premature optimization
# - staticcheck consumes too much RAM and CPU cycles
# - gochecknoglobals is incompatible with current conventions
# - gochecknoinits is incompatible with current conventions
# TODO(mblotniak): Fix code to pass linters: gocritic, scopelint, stylecheck
linters:
  enable-all: true
  disable:
  - dupl
  - gosec
  - megacheck
  - prealloc
  - staticcheck
  - unparam
  - gochecknoglobals
  - gochecknoinits
  - gocritic
  - scopelint
  - stylecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  nakedret:
    max-func-lines: 5
