run:
  # Concurrency is reduced in order to reduce RAM consumption
  concurrency: 2
  deadline: 30m
  skip-files:
  - .*/usr/local/go[0-9\.]*/src/.*
  - (.*/)?vendor/.*
issues:
  exclude:
  - .* always receives .* # unparam issue
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable-all: true
  disable:
  - bodyclose # TODO(dfurman) - fix code and enable linter
  - dogsled # TODO(dfurman) - fix code and enable linter
  - dupl # - dupl consumes too much RAM and CPU cycles
  - funlen # TODO(dfurman) - fix code and enable linter
  - gochecknoglobals # - gochecknoglobals is incompatible with current conventions
  - gochecknoinits # - gochecknoinits is incompatible with current conventions
  - gocognit # TODO(dfurman) - fix code (if needed) and enable linter
  - gocritic # TODO(dfurman) - fix code and enable linter
  - godox # TODO(dfurman) - fix code and enable linter
  - golint # golint consumer too much CPU cycles, so it is run separately
  - gomnd # TODO(dfurman) - fix code (if needed) and enable linter
  - goprintffuncname # TODO(dfurman) - fix code (if needed) and enable linter
  - gosec # - gosec outputs too many false-positives
  - megacheck # - megacheck uses staticcheck which consumes too much RAM and CPU cycles
  - prealloc # - prealloc issues are considered premature optimization
  - rowserrcheck # TODO(dfurman) - fix code (if needed) and enable linter
  - scopelint # TODO(dfurman) - fix code and enable linter
  - stylecheck # TODO(dfurman) - fix code and enable linter
  - whitespace # TODO(dfurman) - fix code and enable linter
  - wsl # TODO(dfurman) - fix code (if needed) and enable linter
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
    enable-all: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  nakedret:
    max-func-lines: 5
