run:
  # Concurrency is reduced in order to reduce RAM consumption
  concurrency: 2
  deadline: 20m
  skip-dirs: []

issues:
  exclude:
  - .* is always .* # unparam check
  - ^should have a package comment, unless it's in another file for this package$ # golint check
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

# Intentionally disabled linters:
# - megacheck consumes too much RAM and CPU cycles
# - prealloc issues are considered premature optimization
linters:
  enable-all: true
  disable:
  - gocritic # TODO: resolve issues or add to intentionally disabled linters
  - megacheck
  - prealloc
  - scopelint # TODO: resolve issues or add to intentionally disabled linters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  unused:
    check-exported: true
  unparam:
    check-exported: true
  nakedret:
    max-func-lines: 5
