- project:
    name: Juniper/contrail
    check:
      jobs:
        - contrail-go-docker
    gate:
      jobs:
        - contrail-go-docker

- job:
    name: contrail-go-docker
    description: |
      Job that builds and tests Juniper/contrail project.
    voting: True
    parent: contrail-base2
    timeout: 5400
    required-projects:
      - Juniper/contrail
      - Juniper/contrail-ansible-deployer
      - Juniper/contrail-test
      - Juniper/contrail-test-ci
    run: playbooks/contrail-go-docker/run.yaml
    nodeset:
      nodes:
        - name: kolla-aio
          label: c7-systest-ci
    vars:
      setup_docker_registry: false
      docker:
        - image: circleci/golang:1.10
        - image: circleci/mysql:5.7
          name: contrail_mysql
          environment:
            MYSQL_ROOT_PASSWORD: contrail123
        - image: circleci/postgres:10.3-alpine
          name: contrail_postgres
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: contrail123
          command: postgres -c wal_level=logical
        - image: gcr.io/etcd-development/etcd:v3.3.2
          name: contrail_etcd
