- project:
    name: Juniper/contrail
    check:
      jobs:
        - contrail-go-docker
    gate:
      jobs:
        - contrail-go-docker

- job:
    name: contrail-go-docker
    description: |
      Job that builds and tests Juniper/contrail project.
    voting: True
    parent: contrail-src-publish-package-el-base
    required-projects:
      - Juniper/contrail
    run: playbooks/contrail-go-docker/run.yaml
    nodeset:
      nodes:
        - name: builder
          label: centos-7-4-builder
    vars:
      docker:
        - image: circleci/golang:1.10
        - image: circleci/mysql:5.7
          environment:
            MYSQL_ROOT_PASSWORD: contrail123
      - image: circleci/10.3-alpine
        environment:
        - POSTGRES_USER: root
        - POSTGRES_DB: contrail123 
