- project:
    name: Juniper/contrail
    check:
      jobs:
        - contrail-go-docker
        - contrail-go-sanity-centos7-k8s:
            vars:
              control_plane_common_roles:
                - config_database
                - config
                - control
                - webui
              contrail_version: master-latest
              contrail_docker_registry: 10.84.5.81:5000
        - contrail-go-sanity-centos7-kolla-ocata:
            voting: False
            vars:
              contrail_version: master-latest
              contrail_docker_registry: 10.84.5.81:5000
    gate:
      jobs:
        - contrail-go-docker

    experimental:
      jobs:
        - contrail-vnc-build-package-centos74
        - contrail-build-containers-centos7-ocata:
            dependencies:
              - contrail-vnc-build-package-centos74
        - contrail-build-test-containers:
            dependencies:
              - contrail-vnc-build-package-centos74
        - contrail-go-sanity-centos7-k8s:
            dependencies:
              - contrail-build-containers-centos7-ocata
              - contrail-build-test-containers
            vars:
              control_plane_common_roles:
                - config_database
                - config
                - control
                - webui
              openstack_version: ocata
        - contrail-go-sanity-centos7-kolla-ocata:
            dependencies:
              - contrail-build-containers-centos7-ocata
              - contrail-build-test-containers
            vars:
              control_plane_common_roles:
                - config_database
                - config
                - control
                - webui
              openstack_version: ocata

- job:
    name: contrail-go-docker
    description: |
      Job that builds and tests Juniper/contrail project.
    voting: True
    parent: contrail-base2
    timeout: 5400
    required-projects:
      - Juniper/contrail
    run: playbooks/contrail-go-docker/run.yaml
    post-run:
      - playbooks/contrail-go-docker/post.yaml
    nodeset:
      nodes:
        - name: builder
          label: centos-7-4-builder-xxlarge
    vars:
      setup_docker_registry: true
      enable_tpc_repo: false
      docker:
        - image: circleci/golang:1.11
        - image: circleci/mysql:5.7
          name: contrail_mysql
          environment:
            MYSQL_ROOT_PASSWORD: contrail123
        - image: circleci/postgres:10.3-alpine
          name: contrail_postgres
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: contrail123
          command: postgres -c wal_level=logical
        - image: gcr.io/etcd-development/etcd:v3.3.2
          name: contrail_etcd
