- project:
    name: Juniper/contrail
    check:
      jobs:
        - contrail-go-docker
    gate:
      jobs:
        - contrail-go-docker

- job:
    name: contrail-go-docker
    description: |
      Job that builds and tests Juniper/contrail project.
    voting: True
    parent: contrail-base2
    timeout: 5400
    required-projects:
      - Juniper/contrail
    run: playbooks/contrail-go-docker/run.yaml
    nodeset:
      nodes:
        - name: builder
          label: centos-7-4-builder
    vars:
      setup_docker_registry: true
      docker:
        - image: circleci/golang:1.10
        - image: circleci/mysql:5.7
          name: contrail_mysql
          environment:
            MYSQL_ROOT_PASSWORD: contrail123
        - image: circleci/postgres:10.3-alpine
          name: contrail_postgres
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: contrail123 

