// Code generated by contrailschema tool from template sync_refs.tmpl; DO NOT EDIT.

package sink

// resolveReferenceTable returns Event kind from reference table name
func resolveReferenceTable(name string) (typeName, refType string) {
	switch name {
	case "ref_sample_tag":
		return "sample", "tag"
	case "ref_tag_tag":
		return "tag", "tag"

	}
	return "", ""
}
