# Database configuration. Only MySQL supported
database:
    connection: "root:contrail123@tcp(localhost:3306)/contrail_test"
    # Max Open Connections for MySQL Server
    max_open_conn: 100
    dialect: mysql

# Log Level
log_level: debug

# Server configuration
server:
    read_timeout: 10
    write_timeout: 5

# Bind addresss
address: ":9091"

# TLS Configuration
tls:
    enabled: true
    key_file: test_data/server.key
    cert_file: test_data/server.crt

# Enable GRPC or not
enable_grpc: true

# Static file config
# key: URL path
# value: file path. (absolute path recommended in production)
static_files:
    public: ../../../public

# API Proxy configuration
# key: URL path
# value: String list of backend host
proxy:
    /contrail:
    - http://localhost:8082

# Keystone configuration
keystone:
    local: true # Enable local keystone v3. This is only for testing now.
    assignment:
        type: static
        file: ./test_data/keystone.yml
    store:
        type: memory
        expire: 3600
    insecure: true
    authurl: https://localhost:9091/v3