name: Multi cloud common resources
description: multi cloud common resources
cleanup:
  - path: /cloud-user/pvt_cloud_user_uuid
  - path: /cloud-user/public_cloud_user_uuid
  - path: /credential/all_in_one_credential_uuid
  - path: /keypair/all_in_one_keypair_uuid

test_data:
  all_in_one_keypair: &all_in_one_keypair
    name: test_pvt_key_real
    uuid: all_in_one_keypair_uuid
    ssh_public_key: test_ssh_key
    ssh_key_dir_path: "./test_data/multicloud"
    parent_type: global-system-config
    parent_uuid: beefbeef-beef-beef-beef-beefbeef0001

  all_in_one_credential: &all_in_one_credential
    name: all_in_one_credential
    uuid: all_in_one_credential_uuid
    ssh_user: test_ssh_user
    ssh_password: test_ssh_password
    keypair_refs:
      - uuid: all_in_one_keypair_uuid
    parent_type: global-system-config
    parent_uuid: beefbeef-beef-beef-beef-beefbeef0001

  pvt_cloud_user: &pvt_cloud_user
    name: pvt_cloud_user
    uuid: pvt_cloud_user_uuid
    credential_refs:
      - uuid: all_in_one_credential_uuid

  public_cloud_user: &public_cloud_user
    name: public_cloud_user
    uuid: public_cloud_user_uuid
    credential_refs:
      - uuid: all_in_one_credential_uuid

clients:
  default:
    id: alice
    password: alice_password
    insecure: true
    scope:
      project:
        name: admin

workflow:
  - name: create keypair
    request:
      path: /keypairs
      method: POST
      expected:
        - 200
      data:
        keypair: *all_in_one_keypair
    expect:
      keypair:
        perms2:
          owner: admin
        uuid: all_in_one_keypair_uuid
        parent_type: global-system-config
        parent_uuid: beefbeef-beef-beef-beef-beefbeef0001
        ssh_public_key: test_ssh_key

  - name: create credential
    request:
      path: /credentials
      method: POST
      expected:
        - 200
      data:
        credential: *all_in_one_credential
    expect:
      credential:
        perms2:
          owner: admin
        uuid: all_in_one_credential_uuid
        parent_type: global-system-config
        parent_uuid: beefbeef-beef-beef-beef-beefbeef0001
        ssh_user: test_ssh_user
        ssh_password: test_ssh_password
        keypair_refs:
          - uuid: all_in_one_keypair_uuid

  - name: create pvt cloud user
    request:
      path: /cloud-users
      method: POST
      expected:
        - 200
      data:
        cloud-user: *pvt_cloud_user
    expect:
      cloud-user:
        name: pvt_cloud_user
        uuid: pvt_cloud_user_uuid
        credential_refs:
          - uuid: all_in_one_credential_uuid

  - name: create public cloud user
    request:
      path: /cloud-users
      method: POST
      expected:
        - 200
      data:
        cloud-user: *public_cloud_user
    expect:
      cloud-user:
        perms2:
          owner: admin
        name: public_cloud_user
        uuid: public_cloud_user_uuid
        credential_refs:
          - uuid: all_in_one_credential_uuid
