---
  prefix: "/"
  api_style: "contrail"
  extends: 
    - "base"
  references: 
    physical_router: 
      operations: "CRUD"
      description: "Network device config of a physical router."
      presence: "optional"
  parents: {}
  plural: "network_device_configs"
  id: "network_device_config"
  schema: 
    required: []
    type: "object"
    properties: {}

