name: QoS Config Test
description: QoS Config test
cleanup:
- path: /qos-config/qos-config-test
- path: /qos-config/qos-config-test-with-valid-entries
test_data:
  qos_config_base: &qos_config_base
    qos_config_type: project
    parent_type: project
    default_forwarding_class_id: 0
    fq_name:
    - default-domain
    - default-project
    - qos-config-test

  qos_config_with_invalid_dscp: &qos_config_with_invalid_dscp
    <<: *qos_config_base
    dscp_entries:
      qos_id_forwarding_class_pair:
      - key: 64
        forwarding_class_id: 0

  qos_config_with_invalid_mpls: &qos_config_with_invalid_mpls
    <<: *qos_config_base
    mpls_exp_entries:
      qos_id_forwarding_class_pair:
      - key: 8
        forwarding_class_id: 0

  qos_config_with_invalid_vlan_priority: &qos_config_with_invalid_vlan_priority
    <<: *qos_config_base
    vlan_priority_entries:
      qos_id_forwarding_class_pair:
      - key: 8
        forwarding_class_id: 0

  qos_config_with_valid_entries: &qos_config_with_valid_entries
    <<: *qos_config_base
    vlan_priority_entries:
      qos_id_forwarding_class_pair:
      - key: 7
        forwarding_class_id: 0
    mpls_exp_entries:
      qos_id_forwarding_class_pair:
      - key: 7
        forwarding_class_id: 0
    dscp_entries:
      qos_id_forwarding_class_pair:
      - key: 8
        forwarding_class_id: 0

clients:
  default:
    id: alice
    password: alice_password
    insecure: true
    scope:
      project:
        name: admin

workflow:
- name: create base QoS Config and check if it has global system config ref added.
  request:
    path: /qos-configs
    method: POST
    expected:
    - 200
    data:
      qos-config:
        <<: *qos_config_base
        uuid: qos-config-test
  expect:
    qos-config:
      <<: *qos_config_base
      global_system_config_refs:
      - to:
        - "default-global-system-config"

- name: delete base QoS Config
  request:
    path: /qos-config/qos-config-test
    method: DELETE
    expected:
    - 200
  expect: null

- name: try to create QoS Config with invalid dscp
  request:
    path: /qos-configs
    method: POST
    expected:
    - 400
    data:
      qos-config:
        <<: *qos_config_with_invalid_dscp
  expect: null

- name: try to create QoS Config with invalid mpls
  request:
    path: /qos-configs
    method: POST
    expected:
    - 400
    data:
      qos-config:
        <<: *qos_config_with_invalid_mpls
  expect: null

- name: try to create QoS Config with invalid vlan_priority
  request:
    path: /qos-configs
    method: POST
    expected:
    - 400
    data:
      qos-config:
        <<: *qos_config_with_invalid_vlan_priority
  expect: null

- name: create QoS Config with valid entries
  request:
    path: /qos-configs
    method: POST
    expected:
    - 200
    data:
      qos-config:
        <<: *qos_config_with_valid_entries
        uuid: qos-config-test-with-valid-entries
  expect:
    qos-config:
      <<: *qos_config_with_valid_entries
      global_system_config_refs:
      - to:
        - "default-global-system-config"

- name: delete QoS Config with valid entries
  request:
    path: /qos-config/qos-config-test-with-valid-entries
    method: DELETE
    expected:
    - 200
  expect: null