---
  plural: "neutron-base"
  prefix: "/neutron/"
  parents: {}
  type: "abstract"
  id: "neutron-base"
  schema:
    required: ["context"]
    type: "object"
    properties:
      context:
        presence: "true"
        $ref: "request.json#/definitions/ReqContext"
        description: "Request context"
