- type: all
  template_path: templates/all.tmpl
  output_path: test_output/all.yml
- type: all
  template_path: templates/hoge_go.tmpl
  output_path: test_output/hoge.go
- type: all
  template_path: templates/hoge_proto.tmpl
  output_path: test_output/hoge.proto
- type: all
  template_path: templates/hoge_sql.tmpl
  output_path: test_output/hoge.sql
