FROM opencontrailnightly/contrail-kubernetes-kube-manager:master-423
MAINTAINER Pawel Marchewka pawel.marchewka@codilime.com

RUN rpm -ihv http://ftp.scientificlinux.org/linux/scientific/7.0/x86_64/os/Packages/patch-2.7.1-8.el7.x86_64.rpm
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py && pip install etcd3
COPY ./files/kube_manager_etcd.patch /tmp/kube_manager_etcd.patch
COPY ./files/entrypoint.sh /
WORKDIR /lib/python2.7/site-packages/
RUN patch -p2 < /tmp/kube_manager_etcd.patch
WORKDIR /etc/contrail