package base

const (
	defaultResource                             = "contrail-cluster"
	defaultResourcePath                         = "/" + defaultResource
	defaultK8sResource                          = "kubernetes-cluster"
	defaultK8sResourcePath                      = "/" + defaultK8sResource
	defaultOpenstackResource                    = "openstack-cluster"
	defaultOpenstackResourcePath                = "/" + defaultOpenstackResource
	defaultVCenterResource                      = "vCenter"
	defaultVCenterResourcePath                  = "/" + defaultVCenterResource
	defaultEndpointRes                          = "endpoint"
	defaultEndpointResPath                      = "/" + defaultEndpointRes
	defaultNodeRes                              = "node"
	defaultNodeResPath                          = "/" + defaultNodeRes
	defaultCredentialRes                        = "credential"
	defaultCredentialResPath                    = "/" + defaultCredentialRes
	defaultKeypairRes                           = "keypair"
	defaultKeypairResPath                       = "/" + defaultKeypairRes
	defaultContrailConfigNodeRes                = "contrail-config-node"
	defaultContrailConfigNodeResPath            = "/" + defaultContrailConfigNodeRes
	defaultContrailConfigDatabaseNodeRes        = "contrail-config-database-node"
	defaultContrailConfigDatabaseNodeResPath    = "/" + defaultContrailConfigDatabaseNodeRes
	defaultContrailControlNodeRes               = "contrail-control-node"
	defaultContrailControlNodeResPath           = "/" + defaultContrailControlNodeRes
	defaultContrailWebuiNodeRes                 = "contrail-webui-node"
	defaultContrailWebuiNodeResPath             = "/" + defaultContrailWebuiNodeRes
	defaultContrailAnalyticsNodeRes             = "contrail-analytics-node"
	defaultContrailAnalyticsNodeResPath         = "/" + defaultContrailAnalyticsNodeRes
	defaultContrailAnalyticsDatabaseNodeRes     = "contrail-analytics-database-node"
	defaultContrailAnalyticsDatabaseNodeResPath = "/" + defaultContrailAnalyticsDatabaseNodeRes
	defaultContrailAnalyticsAlarmNodeRes        = "contrail-analytics-alarm-node"
	defaultContrailAnalyticsAlarmNodeResPath    = "/" + defaultContrailAnalyticsAlarmNodeRes
	defaultContrailAnalyticsSNMPNodeRes         = "contrail-analytics-snmp-node"
	defaultContrailAnalyticsSNMPNodeResPath     = "/" + defaultContrailAnalyticsSNMPNodeRes
	defaultContrailVrouterNodeRes               = "contrail-vrouter-node"
	defaultContrailVrouterNodeResPath           = "/" + defaultContrailVrouterNodeRes
	defaultContrailMCGWNodeRes                  = "contrail-multicloud-gw-node"
	defaultContrailMCGWNodeResPath              = "/" + defaultContrailMCGWNodeRes
	defaultContrailServiceNodeRes               = "contrail-service-node"
	defaultContrailServiceNodeResPath           = "/" + defaultContrailServiceNodeRes
	defaultContrailVCFabricManagerNodeRes       = "contrail-vcenter-fabric-manager-node"
	defaultContrailVCFabricManagerNodeResPath   = "/" + defaultContrailVCFabricManagerNodeRes
	defaultContrailZTPDHCPNodeRes               = "contrail-ztp-dhcp-node"
	defaultContrailZTPDHCPNodeResPath           = "/" + defaultContrailZTPDHCPNodeRes
	defaultContrailZTPTFTPNodeRes               = "contrail-ztp-tftp-node"
	defaultContrailZTPTFTPNodeResPath           = "/" + defaultContrailZTPTFTPNodeRes
	defaultKubernetesNodeRes                    = "kubernetes-node"
	defaultKubernetesNodeResPath                = "/" + defaultKubernetesNodeRes
	defaultKubernetesMasterNodeRes              = "kubernetes-master-node"
	defaultKubernetesMasterNodeResPath          = "/" + defaultKubernetesMasterNodeRes
	defaultKubernetesKubemanagerNodeRes         = "kubernetes-kubemanager-node"
	defaultKubernetesKubemanagerNodeResPath     = "/" + defaultKubernetesKubemanagerNodeRes
	defaultOpenstackControlNodeRes              = "openstack-control-node"
	defaultOpenstackControlNodeResPath          = "/" + defaultOpenstackControlNodeRes
	defaultOpenstackMonitoringNodeRes           = "openstack-monitoring-node"
	defaultOpenstackMonitoringNodeResPath       = "/" + defaultOpenstackMonitoringNodeRes
	defaultOpenstackNetworkNodeRes              = "openstack-network-node"
	defaultOpenstackNetworkNodeResPath          = "/" + defaultOpenstackNetworkNodeRes
	defaultOpenstackStorageNodeRes              = "openstack-storage-node"
	defaultOpenstackStorageNodeResPath          = "/" + defaultOpenstackStorageNodeRes
	defaultOpenstackComputeNodeRes              = "openstack-compute-node"
	defaultOpenstackComputeNodeResPath          = "/" + defaultOpenstackComputeNodeRes
	defaultVCenterComputeRes                    = "vCenter-compute"
	defaultVCenterComputeResPath                = "/" + defaultVCenterComputeRes
	defaultVCenterPluginNodeRes                 = "vCenter-plugin-node"
	defaultVCenterPluginNodeResPath             = "/" + defaultVCenterPluginNodeRes
	defaultVCenterManagerNodeRes                = "vCenter-manager-node"
	defaultVCenterManagerNodeResPath            = "/" + defaultVCenterManagerNodeRes
	defaultAppformixControllerNodeRes           = "appformix-controller-node"
	defaultAppformixControllerNodeResPath       = "/" + defaultAppformixControllerNodeRes
	defaultAppformixBareHostNodeRes             = "appformix-bare-host-node"
	defaultAppformixBareHostNodeResPath         = "/" + defaultAppformixBareHostNodeRes
	defaultAppformixOpenstackNodeRes            = "appformix-openstack-node"
	defaultAppformixOpenstackNodeResPath        = "/" + defaultAppformixOpenstackNodeRes
	defaultAppformixComputeNodeRes              = "appformix-compute-node"
	defaultAppformixComputeNodeResPath          = "/" + defaultAppformixComputeNodeRes
	defaultAppformixNetworkAgentsNodeRes        = "appformix-network-agents-node"
	defaultAppformixNetworkAgentsNodeResPath    = "/" + defaultAppformixNetworkAgentsNodeRes
	openstack                                   = "openstack"
)
