# TODO(nati) use etcd-operator 
{{- if .Values.etcd.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "etcdclient.fullname" . }}
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: {{ template "etcdclient.fullname" . }}
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "etcdclient.fullname" . }}
    etcd_node: {{ template "etcd0.fullname" . }}
  name: {{ template "etcd0.fullname" . }}
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - {{ template "etcd0.fullname" . }}
    - --initial-advertise-peer-urls
    - http://{{ template "etcd0.fullname" . }}:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://{{ template "etcd0.fullname" . }}:2379
    - --initial-cluster
    - {{ template "etcd0.fullname" . }}=http://{{ template "etcd0.fullname" . }}:2380,{{ template "etcd1.fullname" . }}=http://{{ template "etcd1.fullname" . }}:2380,{{ template "etcd2.fullname" . }}=http://{{ template "etcd2.fullname" . }}:2380
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: {{ template "etcd0.fullname" . }}
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: {{ template "etcd0.fullname" . }}
  name: {{ template "etcd0.fullname" . }}
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: {{ template "etcd0.fullname" . }}

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "etcdclient.fullname" . }}
    etcd_node: {{ template "etcd1.fullname" . }}
  name: {{ template "etcd1.fullname" . }}
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - {{ template "etcd1.fullname" . }}
    - --initial-advertise-peer-urls
    - http://{{ template "etcd1.fullname" . }}:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://{{ template "etcd1.fullname" . }}:2379
    - --initial-cluster
    - {{ template "etcd0.fullname" . }}=http://{{ template "etcd0.fullname" . }}:2380,{{ template "etcd1.fullname" . }}=http://{{ template "etcd1.fullname" . }}:2380,{{ template "etcd2.fullname" . }}=http://{{ template "etcd2.fullname" . }}:2380
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: {{ template "etcd1.fullname" . }}
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: {{ template "etcd1.fullname" . }}
  name: {{ template "etcd1.fullname" . }}
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: {{ template "etcd1.fullname" . }}
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ template "etcdclient.fullname" . }}
    etcd_node: {{ template "etcd2.fullname" . }}
  name: {{ template "etcd2.fullname" . }}
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - {{ template "etcd2.fullname" . }}
    - --initial-advertise-peer-urls
    - http://{{ template "etcd2.fullname" . }}:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://{{ template "etcd2.fullname" . }}:2379
    - --initial-cluster
    - {{ template "etcd0.fullname" . }}=http://{{ template "etcd0.fullname" . }}:2380,{{ template "etcd1.fullname" . }}=http://{{ template "etcd1.fullname" . }}:2380,{{ template "etcd2.fullname" . }}=http://{{ template "etcd2.fullname" . }}:2380
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: {{ template "etcd2.fullname" . }}
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: {{ template "etcd2.fullname" . }}
  name: {{ template "etcd2.fullname" . }}
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: {{ template "etcd2.fullname" . }}
{{ end }}