apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-setupdb"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.image }}"
        env:
        - name: PGPASSWORD
          value: {{ .Values.patroni.credentials.admin }}
        command:
        - psql
        - "-h"
        {{- if .Values.patroni.enabled }}
        - "{{ template "patroni.fullname" . }}"
        {{ else }}
        - {{ .Values.patroni.postgresHost }}
        {{ end }}
        - "-U"
        - {{ .Values.patroni.postgresUser | default "admin" }}
        - "-f"
        - /usr/share/contrail/init_psql.sql
        - {{ .Values.patroni.postgresDatabase }}
