-- Code generated by contrailschema tool from template sql_cleanup_psql.tmpl; DO NOT EDIT.

DROP PUBLICATION IF EXISTS "syncpub";

TRUNCATE TABLE metadata, int_pool, ipaddress_pool CASCADE;


TRUNCATE TABLE sample CASCADE;

TRUNCATE TABLE tag CASCADE;

