-- Code generated by contrailschema tool from template sql_mysql.tmpl; DO NOT EDIT.

SET GLOBAL group_concat_max_len=100000;

create table metadata (
    `uuid` varchar(255),
    `type` varchar(255),
    `fq_name` varchar(255),
    primary key (`uuid`),
    UNIQUE(`type`, `fq_name`),
    index fq_name_index (`fq_name`)
 ) CHARACTER SET utf8mb4;

create table int_pool (
    `key` varchar(255),
    `start` int,
    `end` int
);

insert into int_pool (`key`, `start`, `end`) values ("virtual_network_id", 5, 65543);
insert into int_pool (`key`, `start`, `end`) values ("security_group_id", 1, 65543);
-- TODO check range
insert into int_pool (`key`, `start`, `end`) values ("route_target_number", 8000100, 8010002);

create table ipaddress_pool (
    `key` varchar(255),
    `start` binary(16),
    `end` binary(16)
);

create table kv_store (
	`key` varchar(255),
	`value` varchar(255),
	primary key (`key`)
);




create table sample (
    `uuid` varchar(255),
    `share` json,
    `owner_access` bigint,
    `owner` varchar(255),
    `global_access` bigint,
    `parent_uuid` varchar(255),
    `parent_type` varchar(255),
    `name` varchar(255),
    `layout_config` varchar(255),
    `uuid_mslong` bigint,
    `uuid_lslong` bigint,
    `user_visible` bool,
    `permissions_owner_access` bigint,
    `permissions_owner` varchar(255),
    `other_access` bigint,
    `group_access` bigint,
    `group` varchar(255),
    `last_modified` varchar(255),
    `enable` bool,
    `description` varchar(255),
    `creator` varchar(255),
    `created` varchar(255),
    `fq_name` json,
    `display_name` varchar(255),
    `content_config` varchar(255),
    `container_config` varchar(255),
    `configuration_version` bigint,
    `key_value_pair` json,
     primary key(`uuid`),
    index parent_uuid_index (`parent_uuid`)
    ) CHARACTER SET utf8mb4;


create table tag (
    `uuid` varchar(255),
    `tag_value` varchar(255),
    `share` json,
    `owner_access` bigint,
    `owner` varchar(255),
    `global_access` bigint,
    `parent_uuid` varchar(255),
    `parent_type` varchar(255),
    `name` varchar(255),
    `uuid_mslong` bigint,
    `uuid_lslong` bigint,
    `user_visible` bool,
    `permissions_owner_access` bigint,
    `permissions_owner` varchar(255),
    `other_access` bigint,
    `group_access` bigint,
    `group` varchar(255),
    `last_modified` varchar(255),
    `enable` bool,
    `description` varchar(255),
    `creator` varchar(255),
    `created` varchar(255),
    `fq_name` json,
    `display_name` varchar(255),
    `configuration_version` bigint,
    `key_value_pair` json,
     primary key(`uuid`),
    index parent_uuid_index (`parent_uuid`)
    ) CHARACTER SET utf8mb4;







create table ref_sample_tag (
    `from` varchar(255),
    `to` varchar(255),
    primary key (`from`,`to`),
    foreign key (`from`) references sample(uuid) on delete cascade,
    foreign key (`to`) references tag(uuid),
    index from_index (`from`)) CHARACTER SET utf8mb4;




create table tenant_share_sample (
    `uuid` varchar(255),
    `to` varchar(255),
    primary key (`uuid`,`to`),
    `access` integer,
    foreign key (`uuid`) references sample(uuid) on delete cascade,
    foreign key (`to`) references project(uuid) on delete cascade,
    index uuid_index (`uuid`),
    index to_index (`to`)
    ) CHARACTER SET utf8mb4;

create table domain_share_sample (
    `uuid` varchar(255),
    `to` varchar(255),
    primary key (`uuid`,`to`),
    `access` integer,
    foreign key (`uuid`) references sample(uuid) on delete cascade,
    foreign key (`to`) references domain(uuid) on delete cascade,
    index uuid_index (`uuid`),
    index to_index (`to`)
    ) CHARACTER SET utf8mb4;





create table ref_tag_tag (
    `from` varchar(255),
    `to` varchar(255),
    primary key (`from`,`to`),
    foreign key (`from`) references tag(uuid) on delete cascade,
    foreign key (`to`) references tag(uuid),
    index from_index (`from`)) CHARACTER SET utf8mb4;




create table tenant_share_tag (
    `uuid` varchar(255),
    `to` varchar(255),
    primary key (`uuid`,`to`),
    `access` integer,
    foreign key (`uuid`) references tag(uuid) on delete cascade,
    foreign key (`to`) references project(uuid) on delete cascade,
    index uuid_index (`uuid`),
    index to_index (`to`)
    ) CHARACTER SET utf8mb4;

create table domain_share_tag (
    `uuid` varchar(255),
    `to` varchar(255),
    primary key (`uuid`,`to`),
    `access` integer,
    foreign key (`uuid`) references tag(uuid) on delete cascade,
    foreign key (`to`) references domain(uuid) on delete cascade,
    index uuid_index (`uuid`),
    index to_index (`to`)
    ) CHARACTER SET utf8mb4;



