- type: all
  template_path: endpoints.tmpl
  output_path: pkg/openstack/neutron/gen_endpoints.go
- type: all
  template_path: service.tmpl
  output_path: pkg/openstack/neutron/gen_service.go
- type: all
  template_path: model.tmpl
  output_path: pkg/openstack/models/gen_models.go
