database:
  host: localhost
  user: root
  password: contrail123
  name: contrail_test
  max_open_conn: 100
  connection_retries: 10
  retry_period: 3s
  replication_status_timeout: 10s
  debug: false

etcd:
  endpoints:
  - localhost:2379
  username: ""
  password: ""
  path: contrail
  grpc_insecure: true

log_level: debug

homepage:
  enabled: true

server:
  enabled: true
  read_timeout: 10
  write_timeout: 5
  log_api: true
  log_body: true
  enable_vnc_replication: false
  enable_gzip: false
  address: ":9091"
  tls:
    enabled: true
    key_file: test_data/server.key
    cert_file: test_data/server.crt
  enable_grpc: true
  enable_vnc_neutron: true
  static_files:
    public: ../../public
  dynamic_proxy_path: proxy
  proxy:
    /contrail:
    - http://localhost:8082
  notify_etcd: false

sync:
  enabled: true
  storage: json

homepage:
  enabled: true

keystone:
  local: true # Enable local keystone v3. This is only for testing now.
  assignment:
    type: static
    data:
      domains:
        default: &default
          id: default
          name: default
      projects:
        admin: &admin
          id: admin
          name: admin
          domain: *default
        demo: &demo
          id: demo
          name: demo
          domain: *default
        neutron: &neutron
          id: aa907485e1f94a14834d8c69ed9cb3b2
          name: neutron
          domain: *default
      users:
        alice:
          id: alice
          name: Alice
          domain: *default
          password: alice_password
          email: alice@juniper.nets
          roles:
          - id: admin
            name: admin
            project: *admin
          - id: aa907485e1f94a14834d8c69ed9cb3b2
            name: neutron
            project: *neutron

        bob:
          id: bob
          name: Bob
          domain: *default
          password: bob_password
          email: bob@juniper.net
          roles:
          - id: Member
            name: Member
            project: *demo
  store:
    type: memory
    expire: 3600
  insecure: true
  authurl: https://localhost:9091/keystone/v3
