database:
  host: localhost
  user: root
  password: contrail123
  name: contrail_test
  max_open_conn: 100
  connection_retries: 10
  retry_period: 3s
  replication_status_timeout: 10s
  debug: false

etcd:
  endpoints:
  - localhost:2379
  username:
  password:
  path: contrail
  grpc_insecure: true
  tls:
    enabled: false
    certificate_path:
    key_path:
    trusted_ca_path:

log_level: debug

homepage:
  enabled: true

server:
  enabled: true
  read_timeout: 10
  write_timeout: 5
  log_api: true
  log_body: true
  address: ":9091"
  enable_vnc_replication: false
  enable_gzip: false
  tls:
    enabled: true
    key_file: test_data/server.key
    cert_file: test_data/server.crt
  enable_grpc: true
  enable_vnc_neutron: true
  static_files:
    public: ../../public
  dynamic_proxy_path: proxy
  service_token_endpoint_prefixes:
  - swift
  proxy:
    /contrail:
    - http://localhost:8082
  notify_etcd: false

no_auth: true
insecure: true

keystone:
  local: true
  assignment:
    type: static
    data:
      domains:
        default: &default
          id: default
          name: default
      projects:
        admin: &admin
          id: admin
          name: admin
          domain: *default
        demo: &demo
          id: demo
          name: demo
          domain: *default
        neutron: &neutron
          id: aa907485e1f94a14834d8c69ed9cb3b2
          name: neutron
          domain: *default
        service: &service
          id: service
          name: service
          domain: *default
      users:
        admin:
          id: admin
          name: admin
          domain: *default
          password: contrail123
          roles:
          - id: admin
            name: admin
            project: *admin
        alice:
          id: alice
          name: Alice
          domain: *default
          password: alice_password
          email: alice@juniper.nets
          roles:
          - id: admin
            name: admin
            project: *admin
          - id: aa907485e1f94a14834d8c69ed9cb3b2
            name: neutron
            project: *neutron
        bob:
          id: bob
          name: Bob
          domain: *default
          password: bob_password
          email: bob@juniper.net
          roles:
          - id: Member
            name: Member
            project: *demo
        goapi:
          id: goapi-uuid
          name: goapi
          domain: *default
          password: goapi
          roles:
          - id: admin
            name: admin
            project: *service
  store:
    type: memory
    expire: 3600
  insecure: true
  authurl: https://localhost:9091/keystone/v3
  service_user:
    id: goapi
    password: goapi
    project_name: service
    domain_id: default

sync:
  enabled: true
  storage: json
  dump: true

client:
  id: alice
  password: alice_password
  project_id: admin
  domain_id: default
  schema_root: /public
  endpoint: https://localhost:9091

compilation:
  enabled: false

cache:
  enabled: false

replication:
  cassandra:
    enabled: false
  amqp:
    enabled: false
