// Code generated by contrailschema tool from template quota_checker_service.tmpl; DO NOT EDIT.

package services

import (
	"context"

	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"

	"github.com/Juniper/contrail/extension/pkg/models"
	"github.com/Juniper/contrail/pkg/errutil"
)

//preventing import error
var _ = log.Debug
var _ = errutil.ErrorNotFound
var _ = models.Version
var _ = errors.New
var _ context.Context

type QuotaCheckerService struct {
	BaseService
	resourceCounter QuotaResourceCounter
	limitGetter     QuotaLimitGetter
}

// Type Sample is not under quota

// Type Tag is not under quota
