// Code generated by contrailschema tool from template sanitizer_service.tmpl; DO NOT EDIT.

package services

import (
	"bytes"
	"context"
	"fmt"

	"github.com/pkg/errors"

	"github.com/Juniper/contrail/extension/pkg/models"
	"github.com/Juniper/contrail/pkg/errutil"
	"github.com/Juniper/contrail/pkg/models/basemodels"
	"github.com/Juniper/contrail/pkg/services/baseservices"
)

//This is needed to prevent an import error.
var _ = errutil.ErrorNotFound
var _ = models.Version
var _ = basemodels.Metadata{}

// SanitizerService fills up missing properties based on resources logic and metadata
// TODO: Move logic from ContrailService when validation will be a separate service
type SanitizerService struct {
	BaseService
	MetadataGetter baseservices.MetadataGetter
}

func (sv *SanitizerService) sanitizeRefs(
	ctx context.Context,
	refs []basemodels.Reference,
) error {
	fqNameToRef := make(map[string]basemodels.Reference)
	var metadatas []*basemodels.Metadata
	for _, ref := range refs {
		if ref.GetUUID() != "" {
			continue
		}
		fqNameToRef[basemodels.FQNameToString(ref.GetTo())] = ref
		metadatas = append(metadatas, &basemodels.Metadata{FQName: ref.GetTo(), Type: ref.GetReferredKind()})
	}

	if len(metadatas) == 0 {
		return nil
	}

	ml, err := sv.MetadataGetter.ListMetadata(ctx, metadatas)
	if err != nil {
		return err
	}

	if len(ml) != len(metadatas) {
		for _, metadata := range ml {
			delete(fqNameToRef, basemodels.FQNameToString(metadata.FQName))
		}
		var missingRefs bytes.Buffer
		for _, ref := range fqNameToRef {
			missingRefs.WriteString(fmt.Sprintf(" {type: %v, to: %v}", ref.GetReferredKind(), ref.GetTo()))
		}
		return errors.Errorf("couldn't get metadatas for references:%v", missingRefs.String())
	}

	for _, metadata := range ml {
		fqNameToRef[basemodels.FQNameToString(metadata.FQName)].SetUUID(metadata.UUID)
	}
	return nil
}

func (sv *SanitizerService) sanitizeSampleDisplayName(ctx context.Context, m *models.Sample) {
	if m.DisplayName == "" {
		m.DisplayName = m.Name
	}
}

func (sv *SanitizerService) CreateSample(
	ctx context.Context, request *CreateSampleRequest,
) (*CreateSampleResponse, error) {
	m := request.GetSample()
	sv.sanitizeSampleDisplayName(ctx, m)

	if err := sv.sanitizeRefs(ctx, m.GetReferences()); err != nil {
		return nil, errutil.ErrorBadRequestf("couldn't sanitize refs of Sample %v: %v", m.GetUUID(), err)
	}

	return sv.BaseService.CreateSample(ctx, request)
}

func (sv *SanitizerService) UpdateSample(
	ctx context.Context, request *UpdateSampleRequest,
) (*UpdateSampleResponse, error) {

	m := request.GetSample()

	if err := sv.sanitizeRefs(ctx, m.GetReferences()); err != nil {
		return nil, errutil.ErrorBadRequestf("couldn't sanitize refs of Sample %v: %v", m.GetUUID(), err)
	}

	return sv.BaseService.UpdateSample(ctx, request)
}

func (sv *SanitizerService) sanitizeTagDisplayName(ctx context.Context, m *models.Tag) {
	if m.DisplayName == "" {
		m.DisplayName = m.Name
	}
}

func (sv *SanitizerService) CreateTag(
	ctx context.Context, request *CreateTagRequest,
) (*CreateTagResponse, error) {
	m := request.GetTag()
	sv.sanitizeTagDisplayName(ctx, m)

	if err := sv.sanitizeRefs(ctx, m.GetReferences()); err != nil {
		return nil, errutil.ErrorBadRequestf("couldn't sanitize refs of Tag %v: %v", m.GetUUID(), err)
	}

	return sv.BaseService.CreateTag(ctx, request)
}

func (sv *SanitizerService) UpdateTag(
	ctx context.Context, request *UpdateTagRequest,
) (*UpdateTagResponse, error) {

	m := request.GetTag()

	if err := sv.sanitizeRefs(ctx, m.GetReferences()); err != nil {
		return nil, errutil.ErrorBadRequestf("couldn't sanitize refs of Tag %v: %v", m.GetUUID(), err)
	}

	return sv.BaseService.UpdateTag(ctx, request)
}
