// Code generated by contrailschema tool from template base_quota_counter.tmpl; DO NOT EDIT.

package services

import (
	"context"

	log "github.com/sirupsen/logrus"

	"github.com/Juniper/contrail/extension/pkg/models"
	"github.com/Juniper/contrail/pkg/services/baseservices"
)

//preventing import error
var _ = log.Debug
var _ = models.Version
var _ context.Context
var _ baseservices.ListSpec

type QuotaResourceCounter interface {
}

// DummyQuotaCounter is a dummy counter that returns a count of zero for all resources.
// TODO (Kamil): can be removed after quota counting logic is implemented for all resources.
type DummyQuotaCounter struct{}

// SimpleQuotaCounter implements quota counting logic for resources whose only possible parent is project.
type SimpleQuotaCounter struct {
	DummyQuotaCounter
	rs ReadService
}
