// Code generated by contrailschema tool from template base_quota_getter.tmpl; DO NOT EDIT.

package services

import (
	"context"

	log "github.com/sirupsen/logrus"

	"github.com/Juniper/contrail/extension/pkg/models"
)

//preventing import error
var _ = log.Debug
var _ = models.Version
var _ context.Context

// NoQuotaLimit indicates no limit for resource creation.
const NoQuotaLimit = 0

type QuotaLimitGetter interface {
}

// DummyQuotaLimitGetter is a dummy getter that returns no limit for all resources.
// TODO (Kamil): can be removed after getting the quota limit is implemented for all resources.
type DummyQuotaLimitGetter struct{}

// SimpleQuotaLimitGetter implements quota limit getting for resources whose only possible parent is project.
type SimpleQuotaLimitGetter struct {
	DummyQuotaLimitGetter
	rs ReadService
}
