// Code generated by contrailschema tool from template db_types.tmpl; DO NOT EDIT.

package db

import (
	"github.com/Juniper/contrail/pkg/db/basedb"
)

// PermTypeStructure describes PermType structure
var PermTypeStructure = &basedb.Structure{
	"owner":        struct{}{},
	"owner_access": struct{}{},
	"other_access": struct{}{},
	"group":        struct{}{},
	"group_access": struct{}{},
}

// UuidTypeStructure describes UuidType structure
var UuidTypeStructure = &basedb.Structure{
	"uuid_mslong": struct{}{},
	"uuid_lslong": struct{}{},
}

// IdPermsTypeStructure describes IdPermsType structure
var IdPermsTypeStructure = &basedb.Structure{
	"permissions":   PermTypeStructure,
	"uuid":          UuidTypeStructure,
	"enable":        struct{}{},
	"description":   struct{}{},
	"created":       struct{}{},
	"creator":       struct{}{},
	"user_visible":  struct{}{},
	"last_modified": struct{}{},
}

// ShareTypeStructure describes ShareType structure
var ShareTypeStructure = &basedb.Structure{
	"tenant":        struct{}{},
	"tenant_access": struct{}{},
}

// PermType2Structure describes PermType2 structure
var PermType2Structure = &basedb.Structure{
	"owner":         struct{}{},
	"owner_access":  struct{}{},
	"global_access": struct{}{},
	"share":         struct{}{},
}

// KeyValuePairStructure describes KeyValuePair structure
var KeyValuePairStructure = &basedb.Structure{
	"value": struct{}{},
	"key":   struct{}{},
}

// KeyValuePairsStructure describes KeyValuePairs structure
var KeyValuePairsStructure = &basedb.Structure{
	"key_value_pair": struct{}{},
}

// SampleStructure describes Sample structure
var SampleStructure = &basedb.Structure{
	"annotations":           KeyValuePairsStructure,
	"configuration_version": struct{}{},
	"id_perms":              IdPermsTypeStructure,
	"display_name":          struct{}{},
	"perms2":                PermType2Structure,
	"content_config":        struct{}{},
	"layout_config":         struct{}{},
	"parent_type":           struct{}{},
	"uuid":                  struct{}{},
	"parent_uuid":           struct{}{},
	"fq_name":               struct{}{},
	"container_config":      struct{}{},
	"name":                  struct{}{},
}

// TagStructure describes Tag structure
var TagStructure = &basedb.Structure{
	"id_perms":              IdPermsTypeStructure,
	"name":                  struct{}{},
	"annotations":           KeyValuePairsStructure,
	"uuid":                  struct{}{},
	"parent_uuid":           struct{}{},
	"fq_name":               struct{}{},
	"parent_type":           struct{}{},
	"configuration_version": struct{}{},
	"tag_value":             struct{}{},
	"display_name":          struct{}{},
	"perms2":                PermType2Structure,
}
