id: alice
password: alice_password
project_id: admin
#auth_url: http://localhost:9091/v3
endpoint: https://localhost:9091
insecure: true
backend: file
watcher: polling
schema_root: /
log_level: debug
tasks:
- schema_id: contrail_cluster
  common:
  - vars:
      dir: "/var/tmp/{{ resource.schema_id }}/config/{{ resource.uuid }}"
  on_create:
  - debug: "AGENT creating {{ dir }}"
  - command: mkdir -p "{{ dir }}"
  - debug: "AGENT created {{ dir }}"
  - template:
      src: "/etc/contrail/contrail-cluster-config.tmpl"
      dest: "{{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT creating cluster(contrail cluster -c {{ dir }}/contrail-cluster-config.yml)"
  - command: "contrail cluster -c {{ dir }}/contrail-cluster-config.yml"
    #- command: "go run cmd/contrail/main.go cluster -c {{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT cluster create complete"
  on_update:
  - template:
      src: "/etc/contrail/contrail-cluster-config.tmpl"
      dest: "{{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT updating cluster(contrail cluster -c {{ dir }}/contrail-cluster-config.yml)"
  - command: "contrail cluster -c {{ dir }}/contrail-cluster-config.yml"
    #- command: "go run cmd/contrail/main.go cluster -c {{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT cluster update complete"
  on_delete:
  - template:
      src: "/etc/contrail/contrail-cluster-config.tmpl"
      dest: "{{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT deleting cluster(contrail cluster -c {{ dir }}/contrail-cluster-config.yml)"
  - command: "contrail cluster -c {{ dir }}/contrail-cluster-config.yml"
  - debug: "AGENT deleting {{ dir }}"
  - command: "rm -rf  {{ dir }}"
  - debug: "AGENT deleted {{ dir }}"
