- hosts: builder
  name: Gather logs from build and test stage
  roles:
    - zuul-include-vars # include variables exported from trusted context
  vars_files:
    - build-vars.yaml
  tasks:
    - name: Copy logs files
      copy:
        remote_src: yes
        src: "{{ contraildir }}/{{ item }}"
        dest: "{{ logsdir }}/{{ item }}"
        owner: "{{ ansible_env.USER }}"
      when: "{{ contraildir }}/{{ item }} | is_file"
      with_items:
        - linter.log
        - unittests.log
        - coverage.log

- hosts: builder
  roles:
    - contrail-upload-logs-unittests
