- hosts: builder
  name: Gather logs from build and test stage
  roles:
    - zuul-include-vars # include variables exported from trusted context
  vars_files:
    - build-vars.yaml
  tasks:
    - name: Copy logs files
      command: find {{ contraildir }} -type f -name "{{ item }}" -exec cp {} {{ logsdir }} \;
      with_items:
        - linter.log
        - unittests.log
        - coverage.log

- hosts: builder
  roles:
    - contrail-upload-logs-unittests
