global_configuration:
  CONTAINER_REGISTRY: test_registry
  REGISTRY_PRIVATE_INSECURE: True
provider_config:
  bms:
    ssh_user: root
    ssh_pwd: c0ntrail123
    ntpserver: 10.1.1.100
instances:
  all_in_one_node:
    ip: 127.0.0.1
    provider: bms
    roles:
      config:
      config_database:
      control:
      webui:
      analytics:
      analytics_database:
      vcenter_plugin:
  esxi_node:
    ip: 127.0.0.1
    provider: bms
    esxi_host: 10.84.16.11
    roles:
      vrouter:
      vcenter_manager:
        ESXI_USERNAME: root
        ESXI_PASSWORD: c0ntrail123
contrail_configuration:
  CONTRAIL_VERSION: "ocata-5.0-x"
  CLOUD_ORCHESTRATOR: vcenter
  RABBITMQ_NODE_PORT: 5673
  VROUTER_GATEWAY: 127.0.0.254
  VCENTER_SERVER: 10.84.16.51
  VCENTER_USERNAME: administrator
  VCENTER_PASSWORD: Contrail123
  VCENTER_DATACENTER: qa-dc
  VCENTER_DVSWITCH: qa_dvs
  VCENTER_WSDL_PATH: wsdl
  VCENTER_AUTH_PROTOCOL: https
