playbooks/provision_instances.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=openstack
playbooks/configure_instances.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=openstack
playbooks/install_openstack.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=openstack -e force_checkout=yes
playbooks/install_contrail.yml:
  args: -i inventory/ -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e orchestrator=openstack
playbooks/install_appformix.yml:
  args: -e config_file=/tmp/contrail_cluster/test_cluster_uuid/instances.yml -e appformix_version=3.0.0 --skip-tags=install_docker
