- provider: onprem
  organization: dev
  project: test1
  instances:
    - name: bms1
      public_ip: 1.1.1.1
      private_ip: 192.168.1.2
      interface: bond0
      private_subnet:
        - 192.168.1.0/24
      provision: false
      username: root
      password: c0ntrail123
      roles:
        - controller
    - name: bms2
      public_ip: 2.2.2.2
      private_ip: 192.168.1.3
      interface: bond0
      private_subnet:
        - 192.168.1.0/24
      provision: false
      username: root
      password: c0ntrail123
      roles:
        - gateway
