-- Code generated by contrailschema tool from template sql_cleanup_mysql.tmpl; DO NOT EDIT.

SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE metadata;
TRUNCATE TABLE int_pool;
TRUNCATE TABLE ipaddress_pool;


TRUNCATE TABLE access_control_list;
TRUNCATE TABLE tenant_share_access_control_list;
TRUNCATE TABLE domain_share_access_control_list;


TRUNCATE TABLE ref_access_control_list_tag;



TRUNCATE TABLE parent_access_control_list_security_group;

TRUNCATE TABLE parent_access_control_list_virtual_network;



TRUNCATE TABLE address_group;
TRUNCATE TABLE tenant_share_address_group;
TRUNCATE TABLE domain_share_address_group;


TRUNCATE TABLE ref_address_group_tag;



TRUNCATE TABLE parent_address_group_policy_management;

TRUNCATE TABLE parent_address_group_project;



TRUNCATE TABLE alarm;
TRUNCATE TABLE tenant_share_alarm;
TRUNCATE TABLE domain_share_alarm;


TRUNCATE TABLE ref_alarm_tag;



TRUNCATE TABLE parent_alarm_global_system_config;

TRUNCATE TABLE parent_alarm_project;



TRUNCATE TABLE alias_ip_pool;
TRUNCATE TABLE tenant_share_alias_ip_pool;
TRUNCATE TABLE domain_share_alias_ip_pool;


TRUNCATE TABLE ref_alias_ip_pool_tag;



TRUNCATE TABLE parent_alias_ip_pool_virtual_network;



TRUNCATE TABLE alias_ip;
TRUNCATE TABLE tenant_share_alias_ip;
TRUNCATE TABLE domain_share_alias_ip;


TRUNCATE TABLE ref_alias_ip_project;

TRUNCATE TABLE ref_alias_ip_virtual_machine_interface;

TRUNCATE TABLE ref_alias_ip_tag;



TRUNCATE TABLE parent_alias_ip_alias_ip_pool;



TRUNCATE TABLE analytics_node;
TRUNCATE TABLE tenant_share_analytics_node;
TRUNCATE TABLE domain_share_analytics_node;


TRUNCATE TABLE ref_analytics_node_tag;



TRUNCATE TABLE parent_analytics_node_global_system_config;



TRUNCATE TABLE api_access_list;
TRUNCATE TABLE tenant_share_api_access_list;
TRUNCATE TABLE domain_share_api_access_list;


TRUNCATE TABLE ref_api_access_list_tag;



TRUNCATE TABLE parent_api_access_list_project;

TRUNCATE TABLE parent_api_access_list_domain;

TRUNCATE TABLE parent_api_access_list_global_system_config;



TRUNCATE TABLE application_policy_set;
TRUNCATE TABLE tenant_share_application_policy_set;
TRUNCATE TABLE domain_share_application_policy_set;


TRUNCATE TABLE ref_application_policy_set_global_vrouter_config;

TRUNCATE TABLE ref_application_policy_set_tag;

TRUNCATE TABLE ref_application_policy_set_firewall_policy;



TRUNCATE TABLE parent_application_policy_set_policy_management;

TRUNCATE TABLE parent_application_policy_set_project;



TRUNCATE TABLE bgp_as_a_service;
TRUNCATE TABLE tenant_share_bgp_as_a_service;
TRUNCATE TABLE domain_share_bgp_as_a_service;


TRUNCATE TABLE ref_bgp_as_a_service_bgp_router;

TRUNCATE TABLE ref_bgp_as_a_service_service_health_check;

TRUNCATE TABLE ref_bgp_as_a_service_virtual_machine_interface;

TRUNCATE TABLE ref_bgp_as_a_service_tag;



TRUNCATE TABLE parent_bgp_as_a_service_project;



TRUNCATE TABLE bgp_router;
TRUNCATE TABLE tenant_share_bgp_router;
TRUNCATE TABLE domain_share_bgp_router;


TRUNCATE TABLE ref_bgp_router_bgp_router;

TRUNCATE TABLE ref_bgp_router_sub_cluster;

TRUNCATE TABLE ref_bgp_router_tag;



TRUNCATE TABLE parent_bgp_router_routing_instance;



TRUNCATE TABLE bgpvpn;
TRUNCATE TABLE tenant_share_bgpvpn;
TRUNCATE TABLE domain_share_bgpvpn;


TRUNCATE TABLE ref_bgpvpn_tag;



TRUNCATE TABLE parent_bgpvpn_project;



TRUNCATE TABLE bridge_domain;
TRUNCATE TABLE tenant_share_bridge_domain;
TRUNCATE TABLE domain_share_bridge_domain;


TRUNCATE TABLE ref_bridge_domain_tag;



TRUNCATE TABLE parent_bridge_domain_virtual_network;



TRUNCATE TABLE card;
TRUNCATE TABLE tenant_share_card;
TRUNCATE TABLE domain_share_card;


TRUNCATE TABLE ref_card_tag;





TRUNCATE TABLE config_node;
TRUNCATE TABLE tenant_share_config_node;
TRUNCATE TABLE domain_share_config_node;


TRUNCATE TABLE ref_config_node_tag;



TRUNCATE TABLE parent_config_node_global_system_config;



TRUNCATE TABLE config_root;
TRUNCATE TABLE tenant_share_config_root;
TRUNCATE TABLE domain_share_config_root;


TRUNCATE TABLE ref_config_root_tag;





TRUNCATE TABLE customer_attachment;
TRUNCATE TABLE tenant_share_customer_attachment;
TRUNCATE TABLE domain_share_customer_attachment;


TRUNCATE TABLE ref_customer_attachment_floating_ip;

TRUNCATE TABLE ref_customer_attachment_virtual_machine_interface;

TRUNCATE TABLE ref_customer_attachment_tag;





TRUNCATE TABLE database_node;
TRUNCATE TABLE tenant_share_database_node;
TRUNCATE TABLE domain_share_database_node;


TRUNCATE TABLE ref_database_node_tag;



TRUNCATE TABLE parent_database_node_global_system_config;



TRUNCATE TABLE device_image;
TRUNCATE TABLE tenant_share_device_image;
TRUNCATE TABLE domain_share_device_image;


TRUNCATE TABLE ref_device_image_tag;



TRUNCATE TABLE parent_device_image_global_system_config;



TRUNCATE TABLE discovery_service_assignment;
TRUNCATE TABLE tenant_share_discovery_service_assignment;
TRUNCATE TABLE domain_share_discovery_service_assignment;


TRUNCATE TABLE ref_discovery_service_assignment_tag;





TRUNCATE TABLE domain;
TRUNCATE TABLE tenant_share_domain;
TRUNCATE TABLE domain_share_domain;


TRUNCATE TABLE ref_domain_tag;





TRUNCATE TABLE dsa_rule;
TRUNCATE TABLE tenant_share_dsa_rule;
TRUNCATE TABLE domain_share_dsa_rule;


TRUNCATE TABLE ref_dsa_rule_tag;



TRUNCATE TABLE parent_dsa_rule_discovery_service_assignment;



TRUNCATE TABLE e2_service_provider;
TRUNCATE TABLE tenant_share_e2_service_provider;
TRUNCATE TABLE domain_share_e2_service_provider;


TRUNCATE TABLE ref_e2_service_provider_tag;

TRUNCATE TABLE ref_e2_service_provider_peering_policy;

TRUNCATE TABLE ref_e2_service_provider_physical_router;





TRUNCATE TABLE fabric_namespace;
TRUNCATE TABLE tenant_share_fabric_namespace;
TRUNCATE TABLE domain_share_fabric_namespace;


TRUNCATE TABLE ref_fabric_namespace_tag;



TRUNCATE TABLE parent_fabric_namespace_fabric;



TRUNCATE TABLE fabric;
TRUNCATE TABLE tenant_share_fabric;
TRUNCATE TABLE domain_share_fabric;


TRUNCATE TABLE ref_fabric_virtual_network;

TRUNCATE TABLE ref_fabric_tag;

TRUNCATE TABLE ref_fabric_node_profile;



TRUNCATE TABLE parent_fabric_global_system_config;



TRUNCATE TABLE firewall_policy;
TRUNCATE TABLE tenant_share_firewall_policy;
TRUNCATE TABLE domain_share_firewall_policy;


TRUNCATE TABLE ref_firewall_policy_firewall_rule;

TRUNCATE TABLE ref_firewall_policy_security_logging_object;

TRUNCATE TABLE ref_firewall_policy_tag;



TRUNCATE TABLE parent_firewall_policy_policy_management;

TRUNCATE TABLE parent_firewall_policy_project;



TRUNCATE TABLE firewall_rule;
TRUNCATE TABLE tenant_share_firewall_rule;
TRUNCATE TABLE domain_share_firewall_rule;


TRUNCATE TABLE ref_firewall_rule_address_group;

TRUNCATE TABLE ref_firewall_rule_security_logging_object;

TRUNCATE TABLE ref_firewall_rule_service_group;

TRUNCATE TABLE ref_firewall_rule_virtual_network;

TRUNCATE TABLE ref_firewall_rule_tag;



TRUNCATE TABLE parent_firewall_rule_policy_management;

TRUNCATE TABLE parent_firewall_rule_project;



TRUNCATE TABLE floating_ip_pool;
TRUNCATE TABLE tenant_share_floating_ip_pool;
TRUNCATE TABLE domain_share_floating_ip_pool;


TRUNCATE TABLE ref_floating_ip_pool_tag;



TRUNCATE TABLE parent_floating_ip_pool_virtual_network;



TRUNCATE TABLE floating_ip;
TRUNCATE TABLE tenant_share_floating_ip;
TRUNCATE TABLE domain_share_floating_ip;


TRUNCATE TABLE ref_floating_ip_project;

TRUNCATE TABLE ref_floating_ip_virtual_machine_interface;

TRUNCATE TABLE ref_floating_ip_tag;



TRUNCATE TABLE parent_floating_ip_floating_ip_pool;

TRUNCATE TABLE parent_floating_ip_instance_ip;



TRUNCATE TABLE forwarding_class;
TRUNCATE TABLE tenant_share_forwarding_class;
TRUNCATE TABLE domain_share_forwarding_class;


TRUNCATE TABLE ref_forwarding_class_qos_queue;

TRUNCATE TABLE ref_forwarding_class_tag;



TRUNCATE TABLE parent_forwarding_class_global_qos_config;



TRUNCATE TABLE global_analytics_config;
TRUNCATE TABLE tenant_share_global_analytics_config;
TRUNCATE TABLE domain_share_global_analytics_config;


TRUNCATE TABLE ref_global_analytics_config_tag;



TRUNCATE TABLE parent_global_analytics_config_global_system_config;



TRUNCATE TABLE global_qos_config;
TRUNCATE TABLE tenant_share_global_qos_config;
TRUNCATE TABLE domain_share_global_qos_config;


TRUNCATE TABLE ref_global_qos_config_tag;



TRUNCATE TABLE parent_global_qos_config_global_system_config;



TRUNCATE TABLE global_system_config;
TRUNCATE TABLE tenant_share_global_system_config;
TRUNCATE TABLE domain_share_global_system_config;


TRUNCATE TABLE ref_global_system_config_bgp_router;

TRUNCATE TABLE ref_global_system_config_tag;





TRUNCATE TABLE global_vrouter_config;
TRUNCATE TABLE tenant_share_global_vrouter_config;
TRUNCATE TABLE domain_share_global_vrouter_config;


TRUNCATE TABLE ref_global_vrouter_config_tag;



TRUNCATE TABLE parent_global_vrouter_config_global_system_config;



TRUNCATE TABLE hardware;
TRUNCATE TABLE tenant_share_hardware;
TRUNCATE TABLE domain_share_hardware;


TRUNCATE TABLE ref_hardware_card;

TRUNCATE TABLE ref_hardware_tag;





TRUNCATE TABLE instance_ip;
TRUNCATE TABLE tenant_share_instance_ip;
TRUNCATE TABLE domain_share_instance_ip;


TRUNCATE TABLE ref_instance_ip_tag;

TRUNCATE TABLE ref_instance_ip_logical_interface;

TRUNCATE TABLE ref_instance_ip_network_ipam;

TRUNCATE TABLE ref_instance_ip_physical_router;

TRUNCATE TABLE ref_instance_ip_virtual_machine_interface;

TRUNCATE TABLE ref_instance_ip_virtual_network;

TRUNCATE TABLE ref_instance_ip_virtual_router;





TRUNCATE TABLE interface_route_table;
TRUNCATE TABLE tenant_share_interface_route_table;
TRUNCATE TABLE domain_share_interface_route_table;


TRUNCATE TABLE ref_interface_route_table_service_instance;

TRUNCATE TABLE ref_interface_route_table_tag;



TRUNCATE TABLE parent_interface_route_table_project;



TRUNCATE TABLE job_template;
TRUNCATE TABLE tenant_share_job_template;
TRUNCATE TABLE domain_share_job_template;


TRUNCATE TABLE ref_job_template_tag;



TRUNCATE TABLE parent_job_template_global_system_config;



TRUNCATE TABLE link_aggregation_group;
TRUNCATE TABLE tenant_share_link_aggregation_group;
TRUNCATE TABLE domain_share_link_aggregation_group;


TRUNCATE TABLE ref_link_aggregation_group_physical_interface;

TRUNCATE TABLE ref_link_aggregation_group_tag;



TRUNCATE TABLE parent_link_aggregation_group_physical_router;



TRUNCATE TABLE loadbalancer_healthmonitor;
TRUNCATE TABLE tenant_share_loadbalancer_healthmonitor;
TRUNCATE TABLE domain_share_loadbalancer_healthmonitor;


TRUNCATE TABLE ref_loadbalancer_healthmonitor_tag;



TRUNCATE TABLE parent_loadbalancer_healthmonitor_project;



TRUNCATE TABLE loadbalancer_listener;
TRUNCATE TABLE tenant_share_loadbalancer_listener;
TRUNCATE TABLE domain_share_loadbalancer_listener;


TRUNCATE TABLE ref_loadbalancer_listener_tag;

TRUNCATE TABLE ref_loadbalancer_listener_loadbalancer;



TRUNCATE TABLE parent_loadbalancer_listener_project;



TRUNCATE TABLE loadbalancer_member;
TRUNCATE TABLE tenant_share_loadbalancer_member;
TRUNCATE TABLE domain_share_loadbalancer_member;


TRUNCATE TABLE ref_loadbalancer_member_tag;



TRUNCATE TABLE parent_loadbalancer_member_loadbalancer_pool;



TRUNCATE TABLE loadbalancer_pool;
TRUNCATE TABLE tenant_share_loadbalancer_pool;
TRUNCATE TABLE domain_share_loadbalancer_pool;


TRUNCATE TABLE ref_loadbalancer_pool_tag;

TRUNCATE TABLE ref_loadbalancer_pool_loadbalancer_healthmonitor;

TRUNCATE TABLE ref_loadbalancer_pool_loadbalancer_listener;

TRUNCATE TABLE ref_loadbalancer_pool_service_appliance_set;

TRUNCATE TABLE ref_loadbalancer_pool_service_instance;

TRUNCATE TABLE ref_loadbalancer_pool_virtual_machine_interface;



TRUNCATE TABLE parent_loadbalancer_pool_project;



TRUNCATE TABLE loadbalancer;
TRUNCATE TABLE tenant_share_loadbalancer;
TRUNCATE TABLE domain_share_loadbalancer;


TRUNCATE TABLE ref_loadbalancer_service_instance;

TRUNCATE TABLE ref_loadbalancer_virtual_machine_interface;

TRUNCATE TABLE ref_loadbalancer_tag;

TRUNCATE TABLE ref_loadbalancer_service_appliance_set;



TRUNCATE TABLE parent_loadbalancer_project;



TRUNCATE TABLE logical_interface;
TRUNCATE TABLE tenant_share_logical_interface;
TRUNCATE TABLE domain_share_logical_interface;


TRUNCATE TABLE ref_logical_interface_virtual_machine_interface;

TRUNCATE TABLE ref_logical_interface_tag;



TRUNCATE TABLE parent_logical_interface_physical_interface;

TRUNCATE TABLE parent_logical_interface_physical_router;



TRUNCATE TABLE logical_router;
TRUNCATE TABLE tenant_share_logical_router;
TRUNCATE TABLE domain_share_logical_router;


TRUNCATE TABLE ref_logical_router_physical_router;

TRUNCATE TABLE ref_logical_router_route_table;

TRUNCATE TABLE ref_logical_router_route_target;

TRUNCATE TABLE ref_logical_router_service_instance;

TRUNCATE TABLE ref_logical_router_virtual_machine_interface;

TRUNCATE TABLE ref_logical_router_virtual_network;

TRUNCATE TABLE ref_logical_router_tag;

TRUNCATE TABLE ref_logical_router_bgpvpn;



TRUNCATE TABLE parent_logical_router_project;



TRUNCATE TABLE multicast_group_address;
TRUNCATE TABLE tenant_share_multicast_group_address;
TRUNCATE TABLE domain_share_multicast_group_address;


TRUNCATE TABLE ref_multicast_group_address_tag;





TRUNCATE TABLE multicast_group;
TRUNCATE TABLE tenant_share_multicast_group;
TRUNCATE TABLE domain_share_multicast_group;


TRUNCATE TABLE ref_multicast_group_multicast_group_address;

TRUNCATE TABLE ref_multicast_group_tag;





TRUNCATE TABLE multicast_policy;
TRUNCATE TABLE tenant_share_multicast_policy;
TRUNCATE TABLE domain_share_multicast_policy;


TRUNCATE TABLE ref_multicast_policy_tag;





TRUNCATE TABLE namespace;
TRUNCATE TABLE tenant_share_namespace;
TRUNCATE TABLE domain_share_namespace;


TRUNCATE TABLE ref_namespace_tag;



TRUNCATE TABLE parent_namespace_domain;



TRUNCATE TABLE network_device_config;
TRUNCATE TABLE tenant_share_network_device_config;
TRUNCATE TABLE domain_share_network_device_config;


TRUNCATE TABLE ref_network_device_config_physical_router;

TRUNCATE TABLE ref_network_device_config_tag;





TRUNCATE TABLE network_ipam;
TRUNCATE TABLE tenant_share_network_ipam;
TRUNCATE TABLE domain_share_network_ipam;


TRUNCATE TABLE ref_network_ipam_virtual_dns;

TRUNCATE TABLE ref_network_ipam_tag;



TRUNCATE TABLE parent_network_ipam_project;



TRUNCATE TABLE network_policy;
TRUNCATE TABLE tenant_share_network_policy;
TRUNCATE TABLE domain_share_network_policy;


TRUNCATE TABLE ref_network_policy_tag;



TRUNCATE TABLE parent_network_policy_project;



TRUNCATE TABLE node_profile;
TRUNCATE TABLE tenant_share_node_profile;
TRUNCATE TABLE domain_share_node_profile;


TRUNCATE TABLE ref_node_profile_hardware;

TRUNCATE TABLE ref_node_profile_tag;



TRUNCATE TABLE parent_node_profile_global_system_config;



TRUNCATE TABLE peering_policy;
TRUNCATE TABLE tenant_share_peering_policy;
TRUNCATE TABLE domain_share_peering_policy;


TRUNCATE TABLE ref_peering_policy_tag;





TRUNCATE TABLE physical_interface;
TRUNCATE TABLE tenant_share_physical_interface;
TRUNCATE TABLE domain_share_physical_interface;


TRUNCATE TABLE ref_physical_interface_physical_interface;

TRUNCATE TABLE ref_physical_interface_tag;



TRUNCATE TABLE parent_physical_interface_physical_router;



TRUNCATE TABLE physical_router;
TRUNCATE TABLE tenant_share_physical_router;
TRUNCATE TABLE domain_share_physical_router;


TRUNCATE TABLE ref_physical_router_bgp_router;

TRUNCATE TABLE ref_physical_router_device_image;

TRUNCATE TABLE ref_physical_router_fabric;

TRUNCATE TABLE ref_physical_router_node_profile;

TRUNCATE TABLE ref_physical_router_virtual_network;

TRUNCATE TABLE ref_physical_router_virtual_router;

TRUNCATE TABLE ref_physical_router_tag;



TRUNCATE TABLE parent_physical_router_global_system_config;



TRUNCATE TABLE policy_management;
TRUNCATE TABLE tenant_share_policy_management;
TRUNCATE TABLE domain_share_policy_management;


TRUNCATE TABLE ref_policy_management_tag;



TRUNCATE TABLE parent_policy_management_project;



TRUNCATE TABLE port_tuple;
TRUNCATE TABLE tenant_share_port_tuple;
TRUNCATE TABLE domain_share_port_tuple;


TRUNCATE TABLE ref_port_tuple_tag;



TRUNCATE TABLE parent_port_tuple_service_instance;



TRUNCATE TABLE project;
TRUNCATE TABLE tenant_share_project;
TRUNCATE TABLE domain_share_project;


TRUNCATE TABLE ref_project_alias_ip_pool;

TRUNCATE TABLE ref_project_application_policy_set;

TRUNCATE TABLE ref_project_floating_ip_pool;

TRUNCATE TABLE ref_project_namespace;

TRUNCATE TABLE ref_project_tag;



TRUNCATE TABLE parent_project_domain;



TRUNCATE TABLE provider_attachment;
TRUNCATE TABLE tenant_share_provider_attachment;
TRUNCATE TABLE domain_share_provider_attachment;


TRUNCATE TABLE ref_provider_attachment_virtual_router;

TRUNCATE TABLE ref_provider_attachment_tag;





TRUNCATE TABLE qos_config;
TRUNCATE TABLE tenant_share_qos_config;
TRUNCATE TABLE domain_share_qos_config;


TRUNCATE TABLE ref_qos_config_global_system_config;

TRUNCATE TABLE ref_qos_config_tag;



TRUNCATE TABLE parent_qos_config_global_qos_config;

TRUNCATE TABLE parent_qos_config_project;



TRUNCATE TABLE qos_queue;
TRUNCATE TABLE tenant_share_qos_queue;
TRUNCATE TABLE domain_share_qos_queue;


TRUNCATE TABLE ref_qos_queue_tag;



TRUNCATE TABLE parent_qos_queue_global_qos_config;



TRUNCATE TABLE role_config;
TRUNCATE TABLE tenant_share_role_config;
TRUNCATE TABLE domain_share_role_config;


TRUNCATE TABLE ref_role_config_job_template;

TRUNCATE TABLE ref_role_config_tag;



TRUNCATE TABLE parent_role_config_node_profile;



TRUNCATE TABLE route_aggregate;
TRUNCATE TABLE tenant_share_route_aggregate;
TRUNCATE TABLE domain_share_route_aggregate;


TRUNCATE TABLE ref_route_aggregate_routing_instance;

TRUNCATE TABLE ref_route_aggregate_service_instance;

TRUNCATE TABLE ref_route_aggregate_tag;



TRUNCATE TABLE parent_route_aggregate_project;



TRUNCATE TABLE route_table;
TRUNCATE TABLE tenant_share_route_table;
TRUNCATE TABLE domain_share_route_table;


TRUNCATE TABLE ref_route_table_tag;



TRUNCATE TABLE parent_route_table_project;



TRUNCATE TABLE route_target;
TRUNCATE TABLE tenant_share_route_target;
TRUNCATE TABLE domain_share_route_target;


TRUNCATE TABLE ref_route_target_tag;





TRUNCATE TABLE routing_instance;
TRUNCATE TABLE tenant_share_routing_instance;
TRUNCATE TABLE domain_share_routing_instance;


TRUNCATE TABLE ref_routing_instance_route_target;

TRUNCATE TABLE ref_routing_instance_routing_instance;

TRUNCATE TABLE ref_routing_instance_tag;



TRUNCATE TABLE parent_routing_instance_virtual_network;



TRUNCATE TABLE routing_policy;
TRUNCATE TABLE tenant_share_routing_policy;
TRUNCATE TABLE domain_share_routing_policy;


TRUNCATE TABLE ref_routing_policy_routing_instance;

TRUNCATE TABLE ref_routing_policy_service_instance;

TRUNCATE TABLE ref_routing_policy_tag;



TRUNCATE TABLE parent_routing_policy_project;



TRUNCATE TABLE security_group;
TRUNCATE TABLE tenant_share_security_group;
TRUNCATE TABLE domain_share_security_group;


TRUNCATE TABLE ref_security_group_tag;



TRUNCATE TABLE parent_security_group_project;



TRUNCATE TABLE security_logging_object;
TRUNCATE TABLE tenant_share_security_logging_object;
TRUNCATE TABLE domain_share_security_logging_object;


TRUNCATE TABLE ref_security_logging_object_tag;

TRUNCATE TABLE ref_security_logging_object_network_policy;

TRUNCATE TABLE ref_security_logging_object_security_group;



TRUNCATE TABLE parent_security_logging_object_global_vrouter_config;

TRUNCATE TABLE parent_security_logging_object_project;



TRUNCATE TABLE service_appliance;
TRUNCATE TABLE tenant_share_service_appliance;
TRUNCATE TABLE domain_share_service_appliance;


TRUNCATE TABLE ref_service_appliance_physical_interface;

TRUNCATE TABLE ref_service_appliance_tag;



TRUNCATE TABLE parent_service_appliance_service_appliance_set;



TRUNCATE TABLE service_appliance_set;
TRUNCATE TABLE tenant_share_service_appliance_set;
TRUNCATE TABLE domain_share_service_appliance_set;


TRUNCATE TABLE ref_service_appliance_set_tag;



TRUNCATE TABLE parent_service_appliance_set_global_system_config;



TRUNCATE TABLE service_connection_module;
TRUNCATE TABLE tenant_share_service_connection_module;
TRUNCATE TABLE domain_share_service_connection_module;


TRUNCATE TABLE ref_service_connection_module_service_object;

TRUNCATE TABLE ref_service_connection_module_tag;





TRUNCATE TABLE service_endpoint;
TRUNCATE TABLE tenant_share_service_endpoint;
TRUNCATE TABLE domain_share_service_endpoint;


TRUNCATE TABLE ref_service_endpoint_physical_router;

TRUNCATE TABLE ref_service_endpoint_service_connection_module;

TRUNCATE TABLE ref_service_endpoint_service_object;

TRUNCATE TABLE ref_service_endpoint_tag;





TRUNCATE TABLE service_group;
TRUNCATE TABLE tenant_share_service_group;
TRUNCATE TABLE domain_share_service_group;


TRUNCATE TABLE ref_service_group_tag;



TRUNCATE TABLE parent_service_group_policy_management;

TRUNCATE TABLE parent_service_group_project;



TRUNCATE TABLE service_health_check;
TRUNCATE TABLE tenant_share_service_health_check;
TRUNCATE TABLE domain_share_service_health_check;


TRUNCATE TABLE ref_service_health_check_service_instance;

TRUNCATE TABLE ref_service_health_check_tag;



TRUNCATE TABLE parent_service_health_check_project;



TRUNCATE TABLE service_instance;
TRUNCATE TABLE tenant_share_service_instance;
TRUNCATE TABLE domain_share_service_instance;


TRUNCATE TABLE ref_service_instance_service_template;

TRUNCATE TABLE ref_service_instance_tag;

TRUNCATE TABLE ref_service_instance_instance_ip;



TRUNCATE TABLE parent_service_instance_project;



TRUNCATE TABLE service_object;
TRUNCATE TABLE tenant_share_service_object;
TRUNCATE TABLE domain_share_service_object;


TRUNCATE TABLE ref_service_object_tag;





TRUNCATE TABLE service_template;
TRUNCATE TABLE tenant_share_service_template;
TRUNCATE TABLE domain_share_service_template;


TRUNCATE TABLE ref_service_template_service_appliance_set;

TRUNCATE TABLE ref_service_template_tag;



TRUNCATE TABLE parent_service_template_domain;



TRUNCATE TABLE structured_syslog_application_record;
TRUNCATE TABLE tenant_share_structured_syslog_application_record;
TRUNCATE TABLE domain_share_structured_syslog_application_record;


TRUNCATE TABLE ref_structured_syslog_application_record_tag;



TRUNCATE TABLE parent_log_application_record_log_config;



TRUNCATE TABLE structured_syslog_config;
TRUNCATE TABLE tenant_share_structured_syslog_config;
TRUNCATE TABLE domain_share_structured_syslog_config;


TRUNCATE TABLE ref_structured_syslog_config_tag;



TRUNCATE TABLE parent_log_config_global_analytics_config;

TRUNCATE TABLE parent_structured_syslog_config_project;



TRUNCATE TABLE structured_syslog_hostname_record;
TRUNCATE TABLE tenant_share_structured_syslog_hostname_record;
TRUNCATE TABLE domain_share_structured_syslog_hostname_record;


TRUNCATE TABLE ref_structured_syslog_hostname_record_tag;



TRUNCATE TABLE parent_log_hostname_record_log_config;



TRUNCATE TABLE structured_syslog_message;
TRUNCATE TABLE tenant_share_structured_syslog_message;
TRUNCATE TABLE domain_share_structured_syslog_message;


TRUNCATE TABLE ref_structured_syslog_message_tag;



TRUNCATE TABLE parent_log_message_log_config;



TRUNCATE TABLE structured_syslog_sla_profile;
TRUNCATE TABLE tenant_share_structured_syslog_sla_profile;
TRUNCATE TABLE domain_share_structured_syslog_sla_profile;


TRUNCATE TABLE ref_structured_syslog_sla_profile_tag;



TRUNCATE TABLE parent_log_sla_profile_log_config;



TRUNCATE TABLE sub_cluster;
TRUNCATE TABLE tenant_share_sub_cluster;
TRUNCATE TABLE domain_share_sub_cluster;


TRUNCATE TABLE ref_sub_cluster_tag;





TRUNCATE TABLE subnet;
TRUNCATE TABLE tenant_share_subnet;
TRUNCATE TABLE domain_share_subnet;


TRUNCATE TABLE ref_subnet_virtual_machine_interface;

TRUNCATE TABLE ref_subnet_tag;





TRUNCATE TABLE tag;
TRUNCATE TABLE tenant_share_tag;
TRUNCATE TABLE domain_share_tag;


TRUNCATE TABLE ref_tag_tag_type;

TRUNCATE TABLE ref_tag_tag;



TRUNCATE TABLE parent_tag_project;



TRUNCATE TABLE tag_type;
TRUNCATE TABLE tenant_share_tag_type;
TRUNCATE TABLE domain_share_tag_type;


TRUNCATE TABLE ref_tag_type_tag;





TRUNCATE TABLE virtual_dns_record;
TRUNCATE TABLE tenant_share_virtual_dns_record;
TRUNCATE TABLE domain_share_virtual_dns_record;


TRUNCATE TABLE ref_virtual_dns_record_tag;



TRUNCATE TABLE parent_virtual_dns_record_virtual_dns;



TRUNCATE TABLE virtual_dns;
TRUNCATE TABLE tenant_share_virtual_dns;
TRUNCATE TABLE domain_share_virtual_dns;


TRUNCATE TABLE ref_virtual_dns_tag;



TRUNCATE TABLE parent_virtual_dns_domain;



TRUNCATE TABLE virtual_ip;
TRUNCATE TABLE tenant_share_virtual_ip;
TRUNCATE TABLE domain_share_virtual_ip;


TRUNCATE TABLE ref_virtual_ip_loadbalancer_pool;

TRUNCATE TABLE ref_virtual_ip_virtual_machine_interface;

TRUNCATE TABLE ref_virtual_ip_tag;



TRUNCATE TABLE parent_virtual_ip_project;



TRUNCATE TABLE virtual_machine_interface;
TRUNCATE TABLE tenant_share_virtual_machine_interface;
TRUNCATE TABLE domain_share_virtual_machine_interface;


TRUNCATE TABLE ref_virtual_machine_interface_port_tuple;

TRUNCATE TABLE ref_virtual_machine_interface_service_endpoint;

TRUNCATE TABLE ref_virtual_machine_interface_interface_route_table;

TRUNCATE TABLE ref_virtual_machine_interface_security_logging_object;

TRUNCATE TABLE ref_v_m_i_v_m_i;

TRUNCATE TABLE ref_virtual_machine_interface_service_health_check;

TRUNCATE TABLE ref_virtual_machine_interface_bgp_router;

TRUNCATE TABLE ref_virtual_machine_interface_bridge_domain;

TRUNCATE TABLE ref_virtual_machine_interface_physical_interface;

TRUNCATE TABLE ref_virtual_machine_interface_qos_config;

TRUNCATE TABLE ref_virtual_machine_interface_routing_instance;

TRUNCATE TABLE ref_virtual_machine_interface_security_group;

TRUNCATE TABLE ref_virtual_machine_interface_virtual_machine;

TRUNCATE TABLE ref_virtual_machine_interface_virtual_network;

TRUNCATE TABLE ref_virtual_machine_interface_tag;



TRUNCATE TABLE parent_virtual_machine_interface_project;

TRUNCATE TABLE parent_virtual_machine_interface_virtual_machine;

TRUNCATE TABLE parent_virtual_machine_interface_virtual_router;



TRUNCATE TABLE virtual_machine;
TRUNCATE TABLE tenant_share_virtual_machine;
TRUNCATE TABLE domain_share_virtual_machine;


TRUNCATE TABLE ref_virtual_machine_service_instance;

TRUNCATE TABLE ref_virtual_machine_tag;





TRUNCATE TABLE virtual_network;
TRUNCATE TABLE tenant_share_virtual_network;
TRUNCATE TABLE domain_share_virtual_network;


TRUNCATE TABLE ref_virtual_network_tag;

TRUNCATE TABLE ref_virtual_network_logical_router;

TRUNCATE TABLE ref_virtual_network_multicast_policy;

TRUNCATE TABLE ref_virtual_network_network_policy;

TRUNCATE TABLE ref_virtual_network_qos_config;

TRUNCATE TABLE ref_virtual_network_route_table;

TRUNCATE TABLE ref_virtual_network_security_logging_object;

TRUNCATE TABLE ref_virtual_network_virtual_network;

TRUNCATE TABLE ref_virtual_network_bgpvpn;

TRUNCATE TABLE ref_virtual_network_network_ipam;

TRUNCATE TABLE ref_virtual_network_routing_policy;



TRUNCATE TABLE parent_virtual_network_project;



TRUNCATE TABLE virtual_router;
TRUNCATE TABLE tenant_share_virtual_router;
TRUNCATE TABLE domain_share_virtual_router;


TRUNCATE TABLE ref_virtual_router_tag;

TRUNCATE TABLE ref_virtual_router_network_ipam;

TRUNCATE TABLE ref_virtual_router_sub_cluster;

TRUNCATE TABLE ref_virtual_router_virtual_machine;



TRUNCATE TABLE parent_virtual_router_global_system_config;



TRUNCATE TABLE appformix_bare_host_node;
TRUNCATE TABLE tenant_share_appformix_bare_host_node;
TRUNCATE TABLE domain_share_appformix_bare_host_node;


TRUNCATE TABLE ref_appformix_bare_host_node_node;

TRUNCATE TABLE ref_appformix_bare_host_node_tag;



TRUNCATE TABLE parent_appformix_bare_host_node_appformix_cluster;



TRUNCATE TABLE appformix_cluster;
TRUNCATE TABLE tenant_share_appformix_cluster;
TRUNCATE TABLE domain_share_appformix_cluster;


TRUNCATE TABLE ref_appformix_cluster_openstack_cluster;

TRUNCATE TABLE ref_appformix_cluster_tag;



TRUNCATE TABLE parent_appformix_cluster_global_system_config;



TRUNCATE TABLE appformix_compute_node;
TRUNCATE TABLE tenant_share_appformix_compute_node;
TRUNCATE TABLE domain_share_appformix_compute_node;


TRUNCATE TABLE ref_appformix_compute_node_node;

TRUNCATE TABLE ref_appformix_compute_node_tag;



TRUNCATE TABLE parent_appformix_compute_node_appformix_cluster;



TRUNCATE TABLE appformix_controller_node;
TRUNCATE TABLE tenant_share_appformix_controller_node;
TRUNCATE TABLE domain_share_appformix_controller_node;


TRUNCATE TABLE ref_appformix_controller_node_node;

TRUNCATE TABLE ref_appformix_controller_node_tag;



TRUNCATE TABLE parent_appformix_controller_node_appformix_cluster;



TRUNCATE TABLE appformix_openstack_node;
TRUNCATE TABLE tenant_share_appformix_openstack_node;
TRUNCATE TABLE domain_share_appformix_openstack_node;


TRUNCATE TABLE ref_appformix_openstack_node_node;

TRUNCATE TABLE ref_appformix_openstack_node_tag;



TRUNCATE TABLE parent_appformix_openstack_node_appformix_cluster;



TRUNCATE TABLE baremetal_node;
TRUNCATE TABLE tenant_share_baremetal_node;
TRUNCATE TABLE domain_share_baremetal_node;


TRUNCATE TABLE ref_baremetal_node_tag;





TRUNCATE TABLE baremetal_port;
TRUNCATE TABLE tenant_share_baremetal_port;
TRUNCATE TABLE domain_share_baremetal_port;


TRUNCATE TABLE ref_baremetal_port_tag;





TRUNCATE TABLE cloud;
TRUNCATE TABLE tenant_share_cloud;
TRUNCATE TABLE domain_share_cloud;


TRUNCATE TABLE ref_cloud_credential;

TRUNCATE TABLE ref_cloud_tag;





TRUNCATE TABLE cloud_account;
TRUNCATE TABLE tenant_share_cloud_account;
TRUNCATE TABLE domain_share_cloud_account;


TRUNCATE TABLE ref_cloud_account_tag;



TRUNCATE TABLE parent_cloud_account_cloud;



TRUNCATE TABLE cloud_private_subnet;
TRUNCATE TABLE tenant_share_cloud_private_subnet;
TRUNCATE TABLE domain_share_cloud_private_subnet;


TRUNCATE TABLE ref_cloud_private_subnet_tag;



TRUNCATE TABLE parent_cloud_private_subnet_virtual_cloud;



TRUNCATE TABLE cloud_project;
TRUNCATE TABLE tenant_share_cloud_project;
TRUNCATE TABLE domain_share_cloud_project;


TRUNCATE TABLE ref_cloud_project_cloud_user;

TRUNCATE TABLE ref_cloud_project_tag;



TRUNCATE TABLE parent_cloud_project_cloud_account;



TRUNCATE TABLE cloud_region;
TRUNCATE TABLE tenant_share_cloud_region;
TRUNCATE TABLE domain_share_cloud_region;


TRUNCATE TABLE ref_cloud_region_tag;



TRUNCATE TABLE parent_cloud_region_cloud;



TRUNCATE TABLE cloud_security_group;
TRUNCATE TABLE tenant_share_cloud_security_group;
TRUNCATE TABLE domain_share_cloud_security_group;


TRUNCATE TABLE ref_cloud_security_group_cloud_private_subnet;

TRUNCATE TABLE ref_cloud_security_group_tag;



TRUNCATE TABLE parent_cloud_security_group_virtual_cloud;



TRUNCATE TABLE cloud_security_group_rule;
TRUNCATE TABLE tenant_share_cloud_security_group_rule;
TRUNCATE TABLE domain_share_cloud_security_group_rule;


TRUNCATE TABLE ref_cloud_security_group_rule_tag;



TRUNCATE TABLE parent_cloud_security_group_rule_cloud_security_group;



TRUNCATE TABLE cloud_user;
TRUNCATE TABLE tenant_share_cloud_user;
TRUNCATE TABLE domain_share_cloud_user;


TRUNCATE TABLE ref_cloud_user_tag;





TRUNCATE TABLE virtual_cloud;
TRUNCATE TABLE tenant_share_virtual_cloud;
TRUNCATE TABLE domain_share_virtual_cloud;


TRUNCATE TABLE ref_virtual_cloud_tag;



TRUNCATE TABLE parent_virtual_cloud_cloud_region;



TRUNCATE TABLE contrail_analytics_database_node;
TRUNCATE TABLE tenant_share_contrail_analytics_database_node;
TRUNCATE TABLE domain_share_contrail_analytics_database_node;


TRUNCATE TABLE ref_contrail_analytics_database_node_node;

TRUNCATE TABLE ref_contrail_analytics_database_node_tag;



TRUNCATE TABLE parent_contrail_analytics_database_node_contrail_cluster;



TRUNCATE TABLE contrail_analytics_node;
TRUNCATE TABLE tenant_share_contrail_analytics_node;
TRUNCATE TABLE domain_share_contrail_analytics_node;


TRUNCATE TABLE ref_contrail_analytics_node_node;

TRUNCATE TABLE ref_contrail_analytics_node_tag;



TRUNCATE TABLE parent_contrail_analytics_node_contrail_cluster;



TRUNCATE TABLE contrail_cluster;
TRUNCATE TABLE tenant_share_contrail_cluster;
TRUNCATE TABLE domain_share_contrail_cluster;


TRUNCATE TABLE ref_contrail_cluster_vcenter;

TRUNCATE TABLE ref_contrail_cluster_appformix_cluster;

TRUNCATE TABLE ref_contrail_cluster_cloud;

TRUNCATE TABLE ref_contrail_cluster_tag;

TRUNCATE TABLE ref_contrail_cluster_openstack_cluster;

TRUNCATE TABLE ref_contrail_cluster_kubernetes_cluster;



TRUNCATE TABLE parent_contrail_cluster_global_system_config;



TRUNCATE TABLE contrail_config_database_node;
TRUNCATE TABLE tenant_share_contrail_config_database_node;
TRUNCATE TABLE domain_share_contrail_config_database_node;


TRUNCATE TABLE ref_contrail_config_database_node_node;

TRUNCATE TABLE ref_contrail_config_database_node_tag;



TRUNCATE TABLE parent_contrail_config_database_node_contrail_cluster;



TRUNCATE TABLE contrail_config_node;
TRUNCATE TABLE tenant_share_contrail_config_node;
TRUNCATE TABLE domain_share_contrail_config_node;


TRUNCATE TABLE ref_contrail_config_node_node;

TRUNCATE TABLE ref_contrail_config_node_tag;



TRUNCATE TABLE parent_contrail_config_node_contrail_cluster;



TRUNCATE TABLE contrail_control_node;
TRUNCATE TABLE tenant_share_contrail_control_node;
TRUNCATE TABLE domain_share_contrail_control_node;


TRUNCATE TABLE ref_contrail_control_node_node;

TRUNCATE TABLE ref_contrail_control_node_tag;



TRUNCATE TABLE parent_contrail_control_node_contrail_cluster;



TRUNCATE TABLE contrail_multicloud_gw_node;
TRUNCATE TABLE tenant_share_contrail_multicloud_gw_node;
TRUNCATE TABLE domain_share_contrail_multicloud_gw_node;


TRUNCATE TABLE ref_contrail_multicloud_gw_node_node;

TRUNCATE TABLE ref_contrail_multicloud_gw_node_tag;



TRUNCATE TABLE parent_contrail_multicloud_gw_node_contrail_cluster;



TRUNCATE TABLE contrail_service_node;
TRUNCATE TABLE tenant_share_contrail_service_node;
TRUNCATE TABLE domain_share_contrail_service_node;


TRUNCATE TABLE ref_contrail_service_node_node;

TRUNCATE TABLE ref_contrail_service_node_tag;



TRUNCATE TABLE parent_contrail_service_node_contrail_cluster;



TRUNCATE TABLE contrail_storage_node;
TRUNCATE TABLE tenant_share_contrail_storage_node;
TRUNCATE TABLE domain_share_contrail_storage_node;


TRUNCATE TABLE ref_contrail_storage_node_node;

TRUNCATE TABLE ref_contrail_storage_node_tag;



TRUNCATE TABLE parent_contrail_storage_node_contrail_cluster;



TRUNCATE TABLE contrail_vrouter_node;
TRUNCATE TABLE tenant_share_contrail_vrouter_node;
TRUNCATE TABLE domain_share_contrail_vrouter_node;


TRUNCATE TABLE ref_contrail_vrouter_node_node;

TRUNCATE TABLE ref_contrail_vrouter_node_tag;



TRUNCATE TABLE parent_contrail_vrouter_node_contrail_cluster;



TRUNCATE TABLE contrail_webui_node;
TRUNCATE TABLE tenant_share_contrail_webui_node;
TRUNCATE TABLE domain_share_contrail_webui_node;


TRUNCATE TABLE ref_contrail_webui_node_node;

TRUNCATE TABLE ref_contrail_webui_node_tag;



TRUNCATE TABLE parent_contrail_webui_node_contrail_cluster;



TRUNCATE TABLE contrail_ztp_dhcp_node;
TRUNCATE TABLE tenant_share_contrail_ztp_dhcp_node;
TRUNCATE TABLE domain_share_contrail_ztp_dhcp_node;


TRUNCATE TABLE ref_contrail_ztp_dhcp_node_node;

TRUNCATE TABLE ref_contrail_ztp_dhcp_node_tag;



TRUNCATE TABLE parent_contrail_ztp_dhcp_node_contrail_cluster;



TRUNCATE TABLE contrail_ztp_tftp_node;
TRUNCATE TABLE tenant_share_contrail_ztp_tftp_node;
TRUNCATE TABLE domain_share_contrail_ztp_tftp_node;


TRUNCATE TABLE ref_contrail_ztp_tftp_node_node;

TRUNCATE TABLE ref_contrail_ztp_tftp_node_tag;



TRUNCATE TABLE parent_contrail_ztp_tftp_node_contrail_cluster;



TRUNCATE TABLE credential;
TRUNCATE TABLE tenant_share_credential;
TRUNCATE TABLE domain_share_credential;


TRUNCATE TABLE ref_credential_keypair;

TRUNCATE TABLE ref_credential_tag;



TRUNCATE TABLE parent_credential_global_system_config;



TRUNCATE TABLE dashboard;
TRUNCATE TABLE tenant_share_dashboard;
TRUNCATE TABLE domain_share_dashboard;


TRUNCATE TABLE ref_dashboard_tag;





TRUNCATE TABLE endpoint;
TRUNCATE TABLE tenant_share_endpoint;
TRUNCATE TABLE domain_share_endpoint;


TRUNCATE TABLE ref_endpoint_tag;



TRUNCATE TABLE parent_endpoint_contrail_cluster;



TRUNCATE TABLE flavor;
TRUNCATE TABLE tenant_share_flavor;
TRUNCATE TABLE domain_share_flavor;


TRUNCATE TABLE ref_flavor_tag;





TRUNCATE TABLE os_image;
TRUNCATE TABLE tenant_share_os_image;
TRUNCATE TABLE domain_share_os_image;


TRUNCATE TABLE ref_os_image_tag;





TRUNCATE TABLE keypair;
TRUNCATE TABLE tenant_share_keypair;
TRUNCATE TABLE domain_share_keypair;


TRUNCATE TABLE ref_keypair_tag;



TRUNCATE TABLE parent_keypair_global_system_config;



TRUNCATE TABLE kubernetes_cluster;
TRUNCATE TABLE tenant_share_kubernetes_cluster;
TRUNCATE TABLE domain_share_kubernetes_cluster;


TRUNCATE TABLE ref_kubernetes_cluster_tag;



TRUNCATE TABLE parent_kubernetes_cluster_global_system_config;



TRUNCATE TABLE kubernetes_kubemanager_node;
TRUNCATE TABLE tenant_share_kubernetes_kubemanager_node;
TRUNCATE TABLE domain_share_kubernetes_kubemanager_node;


TRUNCATE TABLE ref_kubernetes_kubemanager_node_node;

TRUNCATE TABLE ref_kubernetes_kubemanager_node_tag;



TRUNCATE TABLE parent_kubernetes_kubemanager_node_kubernetes_cluster;



TRUNCATE TABLE kubernetes_master_node;
TRUNCATE TABLE tenant_share_kubernetes_master_node;
TRUNCATE TABLE domain_share_kubernetes_master_node;


TRUNCATE TABLE ref_kubernetes_master_node_node;

TRUNCATE TABLE ref_kubernetes_master_node_tag;



TRUNCATE TABLE parent_kubernetes_master_node_kubernetes_cluster;



TRUNCATE TABLE kubernetes_node;
TRUNCATE TABLE tenant_share_kubernetes_node;
TRUNCATE TABLE domain_share_kubernetes_node;


TRUNCATE TABLE ref_kubernetes_node_tag;

TRUNCATE TABLE ref_kubernetes_node_node;



TRUNCATE TABLE parent_kubernetes_node_kubernetes_cluster;



TRUNCATE TABLE node;
TRUNCATE TABLE tenant_share_node;
TRUNCATE TABLE domain_share_node;


TRUNCATE TABLE ref_node_cloud_private_subnet;

TRUNCATE TABLE ref_node_tag;

TRUNCATE TABLE ref_node_credential;

TRUNCATE TABLE ref_node_cloud_security_group;



TRUNCATE TABLE parent_node_virtual_cloud;

TRUNCATE TABLE parent_node_global_system_config;



TRUNCATE TABLE openstack_baremetal_node;
TRUNCATE TABLE tenant_share_openstack_baremetal_node;
TRUNCATE TABLE domain_share_openstack_baremetal_node;


TRUNCATE TABLE ref_openstack_baremetal_node_node;

TRUNCATE TABLE ref_openstack_baremetal_node_tag;



TRUNCATE TABLE parent_openstack_baremetal_node_openstack_cluster;



TRUNCATE TABLE openstack_cluster;
TRUNCATE TABLE tenant_share_openstack_cluster;
TRUNCATE TABLE domain_share_openstack_cluster;


TRUNCATE TABLE ref_openstack_cluster_tag;



TRUNCATE TABLE parent_openstack_cluster_global_system_config;



TRUNCATE TABLE openstack_compute_node;
TRUNCATE TABLE tenant_share_openstack_compute_node;
TRUNCATE TABLE domain_share_openstack_compute_node;


TRUNCATE TABLE ref_openstack_compute_node_node;

TRUNCATE TABLE ref_openstack_compute_node_tag;



TRUNCATE TABLE parent_openstack_compute_node_openstack_cluster;



TRUNCATE TABLE openstack_control_node;
TRUNCATE TABLE tenant_share_openstack_control_node;
TRUNCATE TABLE domain_share_openstack_control_node;


TRUNCATE TABLE ref_openstack_control_node_node;

TRUNCATE TABLE ref_openstack_control_node_tag;



TRUNCATE TABLE parent_openstack_control_node_openstack_cluster;



TRUNCATE TABLE openstack_monitoring_node;
TRUNCATE TABLE tenant_share_openstack_monitoring_node;
TRUNCATE TABLE domain_share_openstack_monitoring_node;


TRUNCATE TABLE ref_openstack_monitoring_node_node;

TRUNCATE TABLE ref_openstack_monitoring_node_tag;



TRUNCATE TABLE parent_openstack_monitoring_node_openstack_cluster;



TRUNCATE TABLE openstack_network_node;
TRUNCATE TABLE tenant_share_openstack_network_node;
TRUNCATE TABLE domain_share_openstack_network_node;


TRUNCATE TABLE ref_openstack_network_node_node;

TRUNCATE TABLE ref_openstack_network_node_tag;



TRUNCATE TABLE parent_openstack_network_node_openstack_cluster;



TRUNCATE TABLE openstack_storage_node;
TRUNCATE TABLE tenant_share_openstack_storage_node;
TRUNCATE TABLE domain_share_openstack_storage_node;


TRUNCATE TABLE ref_openstack_storage_node_node;

TRUNCATE TABLE ref_openstack_storage_node_tag;



TRUNCATE TABLE parent_openstack_storage_node_openstack_cluster;



TRUNCATE TABLE port;
TRUNCATE TABLE tenant_share_port;
TRUNCATE TABLE domain_share_port;


TRUNCATE TABLE ref_port_tag;



TRUNCATE TABLE parent_port_node;



TRUNCATE TABLE port_group;
TRUNCATE TABLE tenant_share_port_group;
TRUNCATE TABLE domain_share_port_group;


TRUNCATE TABLE ref_port_group_port;

TRUNCATE TABLE ref_port_group_tag;



TRUNCATE TABLE parent_port_group_node;



TRUNCATE TABLE server;
TRUNCATE TABLE tenant_share_server;
TRUNCATE TABLE domain_share_server;


TRUNCATE TABLE ref_server_tag;





TRUNCATE TABLE vcenter;
TRUNCATE TABLE tenant_share_vcenter;
TRUNCATE TABLE domain_share_vcenter;


TRUNCATE TABLE ref_vcenter_tag;



TRUNCATE TABLE parent_vcenter_global_system_config;



TRUNCATE TABLE vcenter_compute;
TRUNCATE TABLE tenant_share_vcenter_compute;
TRUNCATE TABLE domain_share_vcenter_compute;


TRUNCATE TABLE ref_vcenter_compute_node;

TRUNCATE TABLE ref_vcenter_compute_tag;



TRUNCATE TABLE parent_vcenter_compute_vcenter;



TRUNCATE TABLE vcenter_plugin_node;
TRUNCATE TABLE tenant_share_vcenter_plugin_node;
TRUNCATE TABLE domain_share_vcenter_plugin_node;


TRUNCATE TABLE ref_vcenter_plugin_node_node;

TRUNCATE TABLE ref_vcenter_plugin_node_tag;



TRUNCATE TABLE parent_vcenter_plugin_node_vcenter;



TRUNCATE TABLE vpn_group;
TRUNCATE TABLE tenant_share_vpn_group;
TRUNCATE TABLE domain_share_vpn_group;


TRUNCATE TABLE ref_vpn_group_cloud;

TRUNCATE TABLE ref_vpn_group_tag;





TRUNCATE TABLE widget;
TRUNCATE TABLE tenant_share_widget;
TRUNCATE TABLE domain_share_widget;


TRUNCATE TABLE ref_widget_tag;






SET FOREIGN_KEY_CHECKS=1;
