# Database configuraion. Only MySQL supported
# Comment out if you are using no DB.
database:
    connection: "root:contrail123@tcp(localhost:3306)/contrail_test"
    # Max Open Connections for MySQL Server
    max_open_conn: 100

# Log Level
log_level: debug

# Server configuraion
server:
    read_timeout: 10
    write_timeout: 5

# Bind addresss
address: ":9091"

# TLS Configuraion
tls:
    enabled: false
    key_file: key
    cert_file: cret

# Static file config
# key: URL path
# value: file path. (absolute path recommended in production)
static_files:
    public: public

# API Proxy configuraion
# key: URL path
# value: String list of backend host
proxy:
    /contrail:
    - http://localhost:8082

#Sync configuraion. Currently only contrail supported.
sync:
    contrail: http://localhost:9091/

#Keystone configuraion
keystone:
    local: true # Enable local keystone v3. This is only for testing now.
    assignment:
        type: static
        file: ./test_data/keystone.yml
    store:
        type: memory
        expire: 3600
    authurl: http://localhost:9091/v3